 /* AUTO-GENERATED FILE.  DO NOT MODIFY.
  *
  * This class was automatically generated by the
  * aapt tool from the resource data it found.  It
  * should not be modified by hand.
  */
 
 package georeduy.client.activities;
 
 public final class R {
     public static final class attr {
     }
     public static final class drawable {
         public static final int cart=0x7f020000;
         public static final int ic_action_search=0x7f020001;
         public static final int ic_launcher=0x7f020002;
         public static final int ic_stat_gcm=0x7f020003;
     }
     public static final class id {
         public static final int LinearLayout01=0x7f070020;
         public static final int LinearLayout02=0x7f070022;
         public static final int LinearLayout03=0x7f070024;
         public static final int LinearLayout1=0x7f07001f;
         public static final int address=0x7f07002e;
         public static final int button_list=0x7f07000a;
         public static final int button_product_add=0x7f070019;
         public static final int button_product_cancel=0x7f07001a;
         public static final int button_product_item=0x7f07001e;
         public static final int button_products_list=0x7f07000b;
         public static final int button_session_login=0x7f070008;
         public static final int button_session_register=0x7f070007;
         public static final int button_session_register_fbk=0x7f070009;
         public static final int button_site_item=0x7f07002d;
         public static final int button_sites_list=0x7f07000c;
         public static final int button_user_item_add=0x7f070032;
         public static final int button_user_item_rem=0x7f070033;
         public static final int button_users_list=0x7f07000d;
         public static final int button_visit_item=0x7f07003c;
         public static final int button_visits_list=0x7f07000e;
         public static final int date=0x7f070003;
         public static final int description=0x7f070001;
         public static final int display=0x7f070006;
         public static final int edittext_comment=0x7f070039;
         public static final int edittext_email=0x7f07002a;
         public static final int edittext_firstname=0x7f070027;
         public static final int edittext_lastname=0x7f070028;
         public static final int edittext_password=0x7f070023;
         public static final int edittext_password1=0x7f070025;
         public static final int edittext_password2=0x7f070026;
         public static final int edittext_username=0x7f070021;
         public static final int fullname=0x7f070036;
         public static final int layout1=0x7f070010;
         public static final int layout2=0x7f070012;
         public static final int layout3=0x7f070014;
         public static final int layout4=0x7f070016;
         public static final int layout5=0x7f070018;
         public static final int layout6=0x7f070029;
         public static final int listView_list=0x7f070005;
         public static final int map_view=0x7f070004;
         public static final int menu_settings=0x7f07003e;
         public static final int name=0x7f070000;
         public static final int options_clear=0x7f07003f;
         public static final int options_exit=0x7f070040;
         public static final int price=0x7f070002;
         public static final int product_id=0x7f07000f;
         public static final int site_id=0x7f07002c;
         public static final int textview_address=0x7f07003a;
         public static final int textview_comment=0x7f070038;
         public static final int textview_date=0x7f07003b;
         public static final int textview_description=0x7f07001c;
         public static final int textview_email=0x7f07002b;
         public static final int textview_fullname=0x7f070031;
         public static final int textview_name=0x7f070011;
         public static final int textview_price=0x7f07001d;
         public static final int textview_pricetotal=0x7f070017;
         public static final int textview_priceunit=0x7f070013;
         public static final int textview_product_id=0x7f07001b;
         public static final int textview_units=0x7f070015;
         public static final int textview_user_id=0x7f07002f;
         public static final int textview_username=0x7f070030;
         public static final int textview_visit_id=0x7f070037;
         public static final int user_id=0x7f070034;
         public static final int username=0x7f070035;
         public static final int visit_id=0x7f07003d;
     }
     public static final class layout {
         public static final int _activity_display_message=0x7f030000;
         public static final int _list_item=0x7f030001;
         public static final int activity_main=0x7f030002;
         public static final int list_activity=0x7f030003;
         public static final int loginlayout=0x7f030004;
         public static final int main=0x7f030005;
         public static final int main_activity=0x7f030006;
         public static final int product_buy_add_item_dialog=0x7f030007;
         public static final int product_detail_activity=0x7f030008;
         public static final int products_list_item=0x7f030009;
         public static final int session_login_activity=0x7f03000a;
         public static final int session_register_activity=0x7f03000b;
         public static final int session_register_fbk1_activity=0x7f03000c;
         public static final int session_register_fbk2_activity=0x7f03000d;
         public static final int sites_list_item=0x7f03000e;
         public static final int user_detail_activity=0x7f03000f;
         public static final int users_list_item=0x7f030010;
         public static final int visit_comment_activity=0x7f030011;
         public static final int visit_detail_activity=0x7f030012;
         public static final int visits_list_item=0x7f030013;
     }
     public static final class menu {
        public static final int activity_main=0x7f060000;
        public static final int options_menu=0x7f060001;
     }
     public static final class string {
         public static final int already_registered=0x7f040003;
         public static final int app_name=0x7f040000;
         public static final int button_accept=0x7f040023;
         public static final int button_add=0x7f040025;
         public static final int button_buy=0x7f040026;
         public static final int button_cancel=0x7f040024;
         public static final int button_product_item=0x7f04002f;
         public static final int button_products_list=0x7f04002b;
         public static final int button_products_list_hint=0x7f040034;
         public static final int button_send=0x7f040027;
         public static final int button_session_login=0x7f040028;
         public static final int button_session_register=0x7f040029;
         public static final int button_session_register_fbk=0x7f04002a;
         public static final int button_site_item=0x7f040030;
         public static final int button_sites_list=0x7f04002c;
         public static final int button_sites_list_hint=0x7f040035;
         /**  buttons 
          */
         public static final int button_teh_list=0x7f040022;
         public static final int button_user_item_add=0x7f040031;
         public static final int button_user_item_rem=0x7f040032;
         public static final int button_users_list=0x7f04002d;
         public static final int button_users_list_hint=0x7f040036;
         public static final int button_visit_item=0x7f040033;
         public static final int button_visits_list=0x7f04002e;
         public static final int button_visits_list_hint=0x7f040037;
         /**  edittexts 
          */
         public static final int edit_text_message=0x7f040038;
         public static final int edittext_session_login_password_hint=0x7f04003a;
         public static final int edittext_session_login_username_hint=0x7f040039;
         public static final int edittext_session_register_email_hint=0x7f040040;
         public static final int edittext_session_register_firstname_hint=0x7f04003c;
         public static final int edittext_session_register_lastname_hint=0x7f04003d;
         public static final int edittext_session_register_password1_hint=0x7f04003e;
         public static final int edittext_session_register_password2_hint=0x7f04003f;
         public static final int edittext_session_register_username_hint=0x7f04003b;
         public static final int edittext_visit_comment_hint=0x7f040041;
         public static final int error_config=0x7f040002;
         public static final int gcm_deleted=0x7f040009;
         public static final int gcm_error=0x7f040007;
         public static final int gcm_message=0x7f040006;
         public static final int gcm_recoverable_error=0x7f040008;
         public static final int gcm_registered=0x7f040004;
         public static final int gcm_unregistered=0x7f040005;
         public static final int hello_world=0x7f040021;
         /**  others 
          */
         public static final int menu_settings=0x7f040053;
         public static final int options_clear=0x7f040011;
         public static final int options_exit=0x7f040012;
         public static final int options_register=0x7f04000f;
         public static final int options_unregister=0x7f040010;
         public static final int register_passwords_do_not_match=0x7f040054;
         public static final int server_register_error=0x7f04000d;
         public static final int server_registered=0x7f04000b;
         public static final int server_registering=0x7f04000a;
         public static final int server_unregister_error=0x7f04000e;
         public static final int server_unregistered=0x7f04000c;
         public static final int textview_address=0x7f04004a;
         public static final int textview_comment=0x7f04004d;
         public static final int textview_date=0x7f04004b;
         public static final int textview_description=0x7f040049;
         public static final int textview_email=0x7f04004c;
         public static final int textview_filler=0x7f040052;
         public static final int textview_firstname=0x7f040044;
         public static final int textview_fullname=0x7f040043;
         public static final int textview_lastname=0x7f040045;
         public static final int textview_name=0x7f040047;
         public static final int textview_password=0x7f040046;
         public static final int textview_price=0x7f04004e;
         public static final int textview_pricetotal=0x7f040050;
         public static final int textview_priceunit=0x7f04004f;
         public static final int textview_title=0x7f040048;
         public static final int textview_units=0x7f040051;
         /**  textviews 
          */
         public static final int textview_username=0x7f040042;
         public static final int title_activity_display_message=0x7f040014;
         public static final int title_activity_list=0x7f040018;
         /**  FIXME: Strings de prueba, revisar 
          */
         public static final int title_activity_main=0x7f040001;
         /**  fin de strings de prueba 
  activity titles 
          */
         public static final int title_activity_main_menu=0x7f040013;
         public static final int title_activity_product_detail=0x7f04001d;
         public static final int title_activity_products_list=0x7f040019;
         public static final int title_activity_session_login=0x7f040015;
         public static final int title_activity_session_register=0x7f040016;
         public static final int title_activity_session_register_fbk=0x7f040017;
         public static final int title_activity_sites_list=0x7f04001a;
         public static final int title_activity_user_detail=0x7f04001e;
         public static final int title_activity_users_list=0x7f04001b;
         public static final int title_activity_visit_comment=0x7f040020;
         public static final int title_activity_visit_detail=0x7f04001f;
         public static final int title_activity_visits_list=0x7f04001c;
     }
     public static final class style {
         public static final int AppTheme=0x7f050000;
     }
 }
