 /*
  * To change this template, choose Tools | Templates
  * and open the template in the editor.
  */
 
 /*
  * CoolEditor.java
  *
  * Created on 10.03.2009, 17:25:56
  */
 
 package de.cismet.tools.gui;
 
 import java.awt.BorderLayout;
 import javax.swing.JComponent;
 import javax.swing.JPanel;
 import javax.swing.border.EmptyBorder;
 import javax.swing.border.EtchedBorder;
 
 /**
  *
  * @author thorsten
  */
 public class CoolEditor extends JPanel implements WrappedComponent{
     private static final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(CoolEditor.class);
     private JComponent originalComponent=null;
     /** Creates new form CoolEditor */
     public CoolEditor() {
         super();
         initComponents();
         pcpMain.setPanContent(panEdit);
         pcpMain.setPanInter(panFooter);
         pcpMain.setPanTitle(panTitleAndIcon);
     }
 
     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
 
         pcpMain = new de.cismet.tools.gui.PureCoolPanel();
         panEdit = new javax.swing.JPanel();
         panTitleAndIcon = new javax.swing.JPanel();
         panFooter = new javax.swing.JPanel();
 
         setLayout(new java.awt.BorderLayout());
 
         pcpMain.setLayout(new java.awt.BorderLayout());
 
         panEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
         panEdit.setOpaque(false);
         panEdit.setLayout(new java.awt.BorderLayout());
         pcpMain.add(panEdit, java.awt.BorderLayout.CENTER);
 
         panTitleAndIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
         panTitleAndIcon.setOpaque(false);
         panTitleAndIcon.setLayout(new java.awt.BorderLayout());
         pcpMain.add(panTitleAndIcon, java.awt.BorderLayout.NORTH);
 
         panFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
         panFooter.setOpaque(false);
         panFooter.setLayout(new java.awt.BorderLayout());
         pcpMain.add(panFooter, java.awt.BorderLayout.SOUTH);
 
         add(pcpMain, java.awt.BorderLayout.CENTER);
     }// </editor-fold>//GEN-END:initComponents
 
     public JPanel getPanEdit() {
         return panEdit;
     }
 
     public JPanel getPanFooter() {
         return panFooter;
     }
 
     public JPanel getPanTitleAndIcon() {
         return panTitleAndIcon;
     }
 
    @Override
     public JComponent getOriginalComponent() {
         return originalComponent;
     }
 
     public void setOriginalComponent(JComponent originalComponent){
         this.originalComponent=originalComponent;
     }
 
 
 
 
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JPanel panEdit;
     private javax.swing.JPanel panFooter;
     private javax.swing.JPanel panTitleAndIcon;
     private de.cismet.tools.gui.PureCoolPanel pcpMain;
     // End of variables declaration//GEN-END:variables
 
 }
