 /* AUTO-GENERATED FILE.  DO NOT MODIFY.
  *
  * This class was automatically generated by the
  * aapt tool from the resource data it found.  It
  * should not be modified by hand.
  */
 
 package ca.ualberta.cmput301f12t05.ufill;
 
 public final class R {
     public static final class attr {
     }
     public static final class drawable {
         public static final int ic_action_search=0x7f020000;
         public static final int ic_launcher=0x7f020001;
         public static final int ufillapp=0x7f020002;
     }
     public static final class id {
         public static final int BinTitle=0x7f070000;
         public static final int BinType=0x7f070001;
         public static final int CameraPhoto=0x7f070025;
         public static final int CompletedBinTitle=0x7f070002;
         public static final int CompletedBinType=0x7f070003;
         public static final int CreateBinDate=0x7f07000c;
         public static final int CreateBinDate_Sharing=0x7f07000b;
         public static final int CreateBinDescriptionIs=0x7f070006;
         public static final int CreateBinEmailSpinner=0x7f070007;
         public static final int CreateBinImage=0x7f07000a;
         public static final int CreateBinName=0x7f070004;
         public static final int CreateBinNameIs=0x7f070005;
         public static final int CreateBinSelectMediaType=0x7f070008;
         public static final int CreateBinShareIt=0x7f07000d;
         public static final int CreateBinSubmit=0x7f07000e;
         public static final int CreateBinText=0x7f070009;
         public static final int EmailNamePrefText=0x7f070010;
         public static final int EmailPref=0x7f07000f;
         public static final int EmailSpinner=0x7f070013;
         public static final int FillBinCompleteText=0x7f070021;
         public static final int FillBinDescription=0x7f070019;
         public static final int FillBinDescriptionIs=0x7f070018;
         public static final int FillBinEmail=0x7f07001a;
         public static final int FillBinEmailIs=0x7f07001b;
         public static final int FillBinName=0x7f070016;
         public static final int FillBinNameIs=0x7f070017;
         public static final int FillBinSubmitBin=0x7f070022;
         public static final int FillBinTakePicture=0x7f070024;
         public static final int FillBinText=0x7f070020;
         public static final int FillBinTimeStamp=0x7f07001c;
         public static final int FillBinTimeStampIs=0x7f07001d;
         public static final int FillBinType=0x7f07001e;
         public static final int FillBinTypeIs=0x7f07001f;
         public static final int ModifyEmailPref=0x7f070012;
         public static final int ModifyEmailPrefText=0x7f070014;
         public static final int button1=0x7f070026;
         public static final int button2=0x7f070027;
         public static final int button3=0x7f070028;
         public static final int button4=0x7f070029;
         public static final int imageView1=0x7f07002a;
         public static final int menu_settings=0x7f07002c;
         public static final int mylayout=0x7f07002b;
         public static final int mylist=0x7f070023;
         public static final int submitModifyEmail=0x7f070015;
         public static final int submitNewEmail=0x7f070011;
     }
     public static final class layout {
         public static final int activity_bin_row=0x7f030000;
         public static final int activity_completed_row=0x7f030001;
         public static final int activity_create_bin=0x7f030002;
         public static final int activity_email_preferences=0x7f030003;
         public static final int activity_fill__bin=0x7f030004;
         public static final int activity_main=0x7f030005;
         public static final int activity_search_bin=0x7f030006;
         public static final int activity_sourcer_row=0x7f030007;
         public static final int activity_stored_bin=0x7f030008;
     }
     public static final class menu {
         public static final int activity_bin_row=0x7f060000;
         public static final int activity_completed_row=0x7f060001;
         public static final int activity_create_bin=0x7f060002;
         public static final int activity_email_preferences=0x7f060003;
         public static final int activity_fill__bin=0x7f060004;
         public static final int activity_main=0x7f060005;
         public static final int activity_search_bin=0x7f060006;
         public static final int activity_sourcer_row=0x7f060007;
         public static final int activity_stored_bin=0x7f060008;
     }
     public static final class string {
         public static final int BinTab1=0x7f040022;
         public static final int BinTab2=0x7f040023;
         public static final int CompletedBinButton=0x7f04001a;
         public static final int CreateBinAudio=0x7f040013;
         public static final int CreateBinButton=0x7f040019;
         public static final int CreateBinDate=0x7f040016;
         public static final int CreateBinDate_Sharing=0x7f040015;
         public static final int CreateBinDescription=0x7f04000f;
         public static final int CreateBinDisplayDate=0x7f040014;
         public static final int CreateBinImage=0x7f040012;
         public static final int CreateBinName=0x7f04000d;
         public static final int CreateBinName_Description=0x7f04000e;
         public static final int CreateBinSelectMediaType=0x7f040010;
         public static final int CreateBinShareIt=0x7f040017;
         public static final int CreateBinSubmit=0x7f040018;
         public static final int CreateBinText=0x7f040011;
         public static final int DeleteBinButton=0x7f04001c;
         public static final int EmailHint=0x7f04002f;
         public static final int EmailPref=0x7f04002e;
         public static final int FillBinDate=0x7f040007;
         public static final int FillBinDelete=0x7f040025;
         public static final int FillBinDescription=0x7f040005;
         public static final int FillBinDescriptionIs=0x7f040008;
         public static final int FillBinEmail=0x7f040006;
         public static final int FillBinFillHint=0x7f040027;
         public static final int FillBinName=0x7f040004;
         public static final int FillBinSubmit=0x7f04000b;
         public static final int FillBinTakePicture=0x7f04000a;
         public static final int FillBinType=0x7f040009;
        public static final int ModifyEmailHint=0x7f040030;
        public static final int ModifyEmailPref=0x7f040031;
         public static final int SearchBinsButton=0x7f04002b;
         public static final int StoredBinsButton=0x7f04001b;
         public static final int app_name=0x7f040000;
         public static final int emailImageBody=0x7f040029;
         public static final int emailSend=0x7f04002c;
         public static final int emailSubj=0x7f040028;
         public static final int emailTextBody=0x7f04002a;
         public static final int hello_world=0x7f040020;
         public static final int menu_settings=0x7f040001;
         public static final int title_activity_bin_row=0x7f040024;
         public static final int title_activity_completed_row=0x7f040026;
         public static final int title_activity_create_bin=0x7f04000c;
         public static final int title_activity_email_preferences=0x7f04002d;
         public static final int title_activity_fill__bin=0x7f040003;
         public static final int title_activity_main=0x7f040002;
         public static final int title_activity_stored_bin=0x7f040021;
         public static final int title_section1=0x7f04001f;
         public static final int title_section2=0x7f04001e;
         public static final int title_section3=0x7f04001d;
     }
     public static final class style {
         public static final int AppTheme=0x7f050000;
     }
 }
