 package org.jfree.chart.testsuite;
 
 import junit.framework.Test;
 import junit.framework.TestCase;
 import junit.framework.TestSuite;
 
 import org.jfree.chart.annotations.junit.CategoryLineAnnotationTests;
 import org.jfree.chart.annotations.junit.CategoryPointerAnnotationTests;
 import org.jfree.chart.annotations.junit.CategoryTextAnnotationTests;
 import org.jfree.chart.annotations.junit.TextAnnotationTests;
 import org.jfree.chart.annotations.junit.XYBoxAnnotationTests;
 import org.jfree.chart.annotations.junit.XYDrawableAnnotationTests;
 import org.jfree.chart.annotations.junit.XYImageAnnotationTests;
 import org.jfree.chart.annotations.junit.XYLineAnnotationTests;
 import org.jfree.chart.annotations.junit.XYPointerAnnotationTests;
 import org.jfree.chart.annotations.junit.XYPolygonAnnotationTests;
 import org.jfree.chart.annotations.junit.XYShapeAnnotationTests;
 import org.jfree.chart.annotations.junit.XYTextAnnotationTests;
 import org.jfree.chart.annotations.junit.XYTitleAnnotationTests;
 import org.jfree.chart.axis.junit.AxisLocationTests;
 import org.jfree.chart.axis.junit.AxisSpaceTests;
 import org.jfree.chart.axis.junit.AxisTests;
 import org.jfree.chart.axis.junit.CategoryAnchorTests;
 import org.jfree.chart.axis.junit.CategoryAxis3DTests;
 import org.jfree.chart.axis.junit.CategoryAxisTests;
 import org.jfree.chart.axis.junit.CategoryLabelPositionTests;
 import org.jfree.chart.axis.junit.CategoryLabelPositionsTests;
 import org.jfree.chart.axis.junit.CategoryLabelWidthTypeTests;
 import org.jfree.chart.axis.junit.CategoryTickTests;
 import org.jfree.chart.axis.junit.ColorBarTests;
 import org.jfree.chart.axis.junit.CyclicNumberAxisTests;
 import org.jfree.chart.axis.junit.DateAxisTests;
 import org.jfree.chart.axis.junit.DateTickMarkPositionTests;
 import org.jfree.chart.axis.junit.DateTickTests;
 import org.jfree.chart.axis.junit.DateTickUnitTests;
 import org.jfree.chart.axis.junit.ExtendedCategoryAxisTests;
 import org.jfree.chart.axis.junit.LogAxisTests;
 import org.jfree.chart.axis.junit.LogarithmicAxisTests;
 import org.jfree.chart.axis.junit.MarkerAxisBandTests;
 import org.jfree.chart.axis.junit.ModuloAxisTests;
 import org.jfree.chart.axis.junit.MonthDateFormatTests;
 import org.jfree.chart.axis.junit.NumberAxis3DTests;
 import org.jfree.chart.axis.junit.NumberAxisTests;
 import org.jfree.chart.axis.junit.NumberTickUnitTests;
 import org.jfree.chart.axis.junit.PeriodAxisLabelInfoTests;
 import org.jfree.chart.axis.junit.PeriodAxisTests;
 import org.jfree.chart.axis.junit.QuarterDateFormatTests;
 import org.jfree.chart.axis.junit.SegmentedTimelineTests;
 import org.jfree.chart.axis.junit.SegmentedTimelineTests2;
 import org.jfree.chart.axis.junit.StandardTickUnitSourceTests;
 import org.jfree.chart.axis.junit.SubCategoryAxisTests;
 import org.jfree.chart.axis.junit.SymbolAxisTests;
 import org.jfree.chart.axis.junit.TickUnitsTests;
 import org.jfree.chart.axis.junit.ValueAxisTests;
 import org.jfree.chart.block.junit.AbstractBlockTests;
 import org.jfree.chart.block.junit.BlockBorderTests;
 import org.jfree.chart.block.junit.BlockContainerTests;
 import org.jfree.chart.block.junit.BorderArrangementTests;
 import org.jfree.chart.block.junit.ColorBlockTests;
 import org.jfree.chart.block.junit.ColumnArrangementTests;
 import org.jfree.chart.block.junit.EmptyBlockTests;
 import org.jfree.chart.block.junit.FlowArrangementTests;
 import org.jfree.chart.block.junit.GridArrangementTests;
 import org.jfree.chart.block.junit.LabelBlockTests;
 import org.jfree.chart.block.junit.LineBorderTests;
 import org.jfree.chart.block.junit.RectangleConstraintTests;
 import org.jfree.chart.editor.DefaultChartEditorTests;
import org.jfree.chart.encoders.KeypointPNGEncoderAdapter;
 import org.jfree.chart.entity.junit.CategoryItemEntityTests;
 import org.jfree.chart.entity.junit.CategoryLabelEntityTests;
 import org.jfree.chart.entity.junit.ContourEntityTests;
 import org.jfree.chart.entity.junit.LegendItemEntityTests;
 import org.jfree.chart.entity.junit.PieSectionEntityTests;
 import org.jfree.chart.entity.junit.StandardEntityCollectionTests;
 import org.jfree.chart.entity.junit.TickLabelEntityTests;
 import org.jfree.chart.entity.junit.XYItemEntityTests;
 import org.jfree.chart.imagemap.junit.DynamicDriveToolTipTagFragmentGeneratorTests;
 import org.jfree.chart.imagemap.junit.ImageMapUtilitiesTests;
 import org.jfree.chart.imagemap.junit.OverLIBToolTipTagFragmentGeneratorTests;
 import org.jfree.chart.imagemap.junit.StandardToolTipTagFragmentGeneratorTests;
 import org.jfree.chart.imagemap.junit.StandardURLTagFragmentGeneratorTests;
 import org.jfree.chart.junit.AreaChartTests;
 import org.jfree.chart.junit.BarChart3DTests;
 import org.jfree.chart.junit.BarChartTests;
 import org.jfree.chart.junit.BoxAndWhiskerChartTests;
 import org.jfree.chart.junit.BubbleChartTests;
 import org.jfree.chart.junit.CandlestickChartTests;
 import org.jfree.chart.junit.ChartFactoryTests;
 import org.jfree.chart.junit.ChartPanelTests;
 import org.jfree.chart.junit.ChartRenderingInfoTests;
 import org.jfree.chart.junit.GanttChartTests;
 import org.jfree.chart.junit.HashUtilitiesTests;
 import org.jfree.chart.junit.HighLowChartTests;
 import org.jfree.chart.junit.HistogramChartTests;
 import org.jfree.chart.junit.JFreeChartTests;
 import org.jfree.chart.junit.LegendItemCollectionTests;
 import org.jfree.chart.junit.LegendItemTests;
 import org.jfree.chart.junit.LineChart3DTests;
 import org.jfree.chart.junit.LineChartTests;
 import org.jfree.chart.junit.MeterChartTests;
 import org.jfree.chart.junit.MouseWheelHandlerTests;
 import org.jfree.chart.junit.PaintMapTests;
 import org.jfree.chart.junit.PieChart3DTests;
 import org.jfree.chart.junit.PieChartTests;
 import org.jfree.chart.junit.ScatterPlotTests;
 import org.jfree.chart.junit.StackedAreaChartTests;
 import org.jfree.chart.junit.StackedBarChart3DTests;
 import org.jfree.chart.junit.StackedBarChartTests;
 import org.jfree.chart.junit.StackedXYAreaChartTests;
 import org.jfree.chart.junit.StandardChartThemeTests;
 import org.jfree.chart.junit.StrokeMapTests;
 import org.jfree.chart.junit.TimeSeriesChartTests;
 import org.jfree.chart.junit.WaferMapChartTests;
 import org.jfree.chart.junit.WaterfallChartTests;
 import org.jfree.chart.junit.WindPlotTests;
 import org.jfree.chart.junit.XYAreaChartTests;
 import org.jfree.chart.junit.XYBarChartTests;
 import org.jfree.chart.junit.XYLineChartTests;
 import org.jfree.chart.junit.XYStepAreaChartTests;
 import org.jfree.chart.junit.XYStepChartTests;
 import org.jfree.chart.labels.junit.BoxAndWhiskerToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.BoxAndWhiskerXYToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.BubbleXYItemLabelGeneratorTests;
 import org.jfree.chart.labels.junit.CustomXYItemLabelGeneratorTests;
 import org.jfree.chart.labels.junit.HighLowItemLabelGeneratorTests;
 import org.jfree.chart.labels.junit.IntervalCategoryItemLabelGeneratorTests;
 import org.jfree.chart.labels.junit.IntervalCategoryToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.ItemLabelAnchorTests;
 import org.jfree.chart.labels.junit.ItemLabelPositionTests;
 import org.jfree.chart.labels.junit.MultipleXYSeriesLabelGeneratorTests;
 import org.jfree.chart.labels.junit.StandardCategoryItemLabelGeneratorTests;
 import org.jfree.chart.labels.junit.StandardCategorySeriesLabelGeneratorTests;
 import org.jfree.chart.labels.junit.StandardCategoryToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.StandardContourToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.StandardPieSectionLabelGeneratorTests;
 import org.jfree.chart.labels.junit.StandardPieToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.StandardXYItemLabelGeneratorTests;
 import org.jfree.chart.labels.junit.StandardXYSeriesLabelGeneratorTests;
 import org.jfree.chart.labels.junit.StandardXYToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.StandardXYZToolTipGeneratorTests;
 import org.jfree.chart.labels.junit.SymbolicXYItemLabelGeneratorTests;
 import org.jfree.chart.needle.junit.ArrowNeedleTests;
 import org.jfree.chart.needle.junit.LineNeedleTests;
 import org.jfree.chart.needle.junit.LongNeedleTests;
 import org.jfree.chart.needle.junit.MeterNeedleTests;
 import org.jfree.chart.needle.junit.MiddlePinNeedleTests;
 import org.jfree.chart.needle.junit.PinNeedleTests;
 import org.jfree.chart.needle.junit.PlumNeedleTests;
 import org.jfree.chart.needle.junit.PointerNeedleTests;
 import org.jfree.chart.needle.junit.ShipNeedleTests;
 import org.jfree.chart.needle.junit.WindNeedleTests;
 import org.jfree.chart.panel.junit.CrosshairOverlayTests;
 import org.jfree.chart.plot.dial.junit.AbstractDialLayerTests;
 import org.jfree.chart.plot.dial.junit.ArcDialFrameTests;
 import org.jfree.chart.plot.dial.junit.DialBackgroundTests;
 import org.jfree.chart.plot.dial.junit.DialCapTests;
 import org.jfree.chart.plot.dial.junit.DialPlotTests;
 import org.jfree.chart.plot.dial.junit.DialPointerTests;
 import org.jfree.chart.plot.dial.junit.DialTextAnnotationTests;
 import org.jfree.chart.plot.dial.junit.DialValueIndicatorTests;
 import org.jfree.chart.plot.dial.junit.StandardDialFrameTests;
 import org.jfree.chart.plot.dial.junit.StandardDialRangeTests;
 import org.jfree.chart.plot.dial.junit.StandardDialScaleTests;
 import org.jfree.chart.plot.junit.CategoryMarkerTests;
 import org.jfree.chart.plot.junit.CategoryPlotTests;
 import org.jfree.chart.plot.junit.ColorPaletteTests;
 import org.jfree.chart.plot.junit.CombinedDomainCategoryPlotTests;
 import org.jfree.chart.plot.junit.CombinedDomainXYPlotTests;
 import org.jfree.chart.plot.junit.CombinedRangeCategoryPlotTests;
 import org.jfree.chart.plot.junit.CombinedRangeXYPlotTests;
 import org.jfree.chart.plot.junit.CompassPlotTests;
 import org.jfree.chart.plot.junit.ContourPlotTests;
 import org.jfree.chart.plot.junit.CrosshairTests;
 import org.jfree.chart.plot.junit.DefaultDrawingSupplierTests;
 import org.jfree.chart.plot.junit.FastScatterPlotTests;
 import org.jfree.chart.plot.junit.IntervalMarkerTests;
 import org.jfree.chart.plot.junit.MarkerTests;
 import org.jfree.chart.plot.junit.MeterIntervalTests;
 import org.jfree.chart.plot.junit.MeterPlotTests;
 import org.jfree.chart.plot.junit.MultiplePiePlotTests;
 import org.jfree.chart.plot.junit.PieLabelRecordTests;
 import org.jfree.chart.plot.junit.PiePlot3DTests;
 import org.jfree.chart.plot.junit.PiePlotTests;
 import org.jfree.chart.plot.junit.PlotOrientationTests;
 import org.jfree.chart.plot.junit.PlotRenderingInfoTests;
 import org.jfree.chart.plot.junit.PlotTests;
 import org.jfree.chart.plot.junit.PolarPlotTests;
 import org.jfree.chart.plot.junit.RingPlotTests;
 import org.jfree.chart.plot.junit.SpiderWebPlotTests;
 import org.jfree.chart.plot.junit.ThermometerPlotTests;
 import org.jfree.chart.plot.junit.ValueMarkerTests;
 import org.jfree.chart.plot.junit.XYPlotTests;
 import org.jfree.chart.renderer.category.junit.AbstractCategoryItemRendererTests;
 import org.jfree.chart.renderer.category.junit.AreaRendererTests;
 import org.jfree.chart.renderer.category.junit.BarRenderer3DTests;
 import org.jfree.chart.renderer.category.junit.BarRendererTests;
 import org.jfree.chart.renderer.category.junit.BoxAndWhiskerRendererTests;
 import org.jfree.chart.renderer.category.junit.CategoryStepRendererTests;
 import org.jfree.chart.renderer.category.junit.DefaultCategoryItemRendererTests;
 import org.jfree.chart.renderer.category.junit.GanttRendererTests;
 import org.jfree.chart.renderer.category.junit.GradientBarPainterTests;
 import org.jfree.chart.renderer.category.junit.GroupedStackedBarRendererTests;
 import org.jfree.chart.renderer.category.junit.IntervalBarRendererTests;
 import org.jfree.chart.renderer.category.junit.LayeredBarRendererTests;
 import org.jfree.chart.renderer.category.junit.LevelRendererTests;
 import org.jfree.chart.renderer.category.junit.LineAndShapeRendererTests;
 import org.jfree.chart.renderer.category.junit.LineRenderer3DTests;
 import org.jfree.chart.renderer.category.junit.MinMaxCategoryRendererTests;
 import org.jfree.chart.renderer.category.junit.ScatterRendererTests;
 import org.jfree.chart.renderer.category.junit.StackedAreaRendererTests;
 import org.jfree.chart.renderer.category.junit.StackedBarRenderer3DTests;
 import org.jfree.chart.renderer.category.junit.StackedBarRendererTests;
 import org.jfree.chart.renderer.category.junit.StandardBarPainterTests;
 import org.jfree.chart.renderer.category.junit.StatisticalBarRendererTests;
 import org.jfree.chart.renderer.category.junit.StatisticalLineAndShapeRendererTests;
 import org.jfree.chart.renderer.category.junit.WaterfallBarRendererTests;
 import org.jfree.chart.renderer.junit.AbstractRendererTests;
 import org.jfree.chart.renderer.junit.AreaRendererEndTypeTests;
 import org.jfree.chart.renderer.junit.DefaultPolarItemRendererTests;
 import org.jfree.chart.renderer.junit.GrayPaintScaleTests;
 import org.jfree.chart.renderer.junit.LookupPaintScaleTests;
 import org.jfree.chart.renderer.junit.OutlierTests;
 import org.jfree.chart.renderer.junit.RendererUtilitiesTests;
 import org.jfree.chart.renderer.xy.junit.AbstractXYItemRendererTests;
 import org.jfree.chart.renderer.xy.junit.CandlestickRendererTests;
 import org.jfree.chart.renderer.xy.junit.ClusteredXYBarRendererTests;
 import org.jfree.chart.renderer.xy.junit.DeviationRendererTests;
 import org.jfree.chart.renderer.xy.junit.GradientXYBarPainterTests;
 import org.jfree.chart.renderer.xy.junit.HighLowRendererTests;
 import org.jfree.chart.renderer.xy.junit.StackedXYAreaRenderer2Tests;
 import org.jfree.chart.renderer.xy.junit.StackedXYAreaRendererTests;
 import org.jfree.chart.renderer.xy.junit.StackedXYBarRendererTests;
 import org.jfree.chart.renderer.xy.junit.StandardXYBarPainterTests;
 import org.jfree.chart.renderer.xy.junit.StandardXYItemRendererTests;
 import org.jfree.chart.renderer.xy.junit.VectorRendererTests;
 import org.jfree.chart.renderer.xy.junit.WindItemRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYAreaRenderer2Tests;
 import org.jfree.chart.renderer.xy.junit.XYAreaRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYBarRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYBlockRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYBoxAndWhiskerRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYBubbleRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYDifferenceRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYDotRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYErrorRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYLine3DRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYLineAndShapeRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYShapeRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYSplineRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYStepAreaRendererTests;
 import org.jfree.chart.renderer.xy.junit.XYStepRendererTests;
 import org.jfree.chart.renderer.xy.junit.YIntervalRendererTests;
 import org.jfree.chart.title.junit.CompositeTitleTests;
 import org.jfree.chart.title.junit.DateTitleTests;
 import org.jfree.chart.title.junit.ImageTitleTests;
 import org.jfree.chart.title.junit.LegendGraphicTests;
 import org.jfree.chart.title.junit.LegendTitleTests;
 import org.jfree.chart.title.junit.PaintScaleLegendTests;
 import org.jfree.chart.title.junit.ShortTextTitleTests;
 import org.jfree.chart.title.junit.TextTitleTests;
 import org.jfree.chart.title.junit.TitleTests;
 import org.jfree.chart.urls.junit.CustomCategoryURLGeneratorTests;
 import org.jfree.chart.urls.junit.CustomPieURLGeneratorTests;
 import org.jfree.chart.urls.junit.CustomXYURLGeneratorTests;
 import org.jfree.chart.urls.junit.StandardCategoryURLGeneratorTests;
 import org.jfree.chart.urls.junit.StandardPieURLGeneratorTests;
 import org.jfree.chart.urls.junit.StandardXYURLGeneratorTests;
 import org.jfree.chart.urls.junit.TimeSeriesURLGeneratorTests;
 import org.jfree.chart.util.junit.HexNumberFormatTests;
 import org.jfree.chart.util.junit.LineUtilitiesTests;
 import org.jfree.chart.util.junit.LogFormatTests;
 import org.jfree.chart.util.junit.ParamChecksTests;
 import org.jfree.chart.util.junit.RelativeDateFormatTests;
 import org.jfree.data.category.junit.CategoryToPieDatasetTests;
 import org.jfree.data.category.junit.DefaultCategoryDatasetTests;
 import org.jfree.data.category.junit.DefaultIntervalCategoryDatasetTests;
 import org.jfree.data.category.junit.SlidingCategoryDatasetTests;
 import org.jfree.data.function.junit.LineFunction2DTests;
 import org.jfree.data.function.junit.NormalDistributionFunction2DTests;
 import org.jfree.data.function.junit.PolynomialFunction2DTests;
 import org.jfree.data.function.junit.PowerFunction2DTests;
 import org.jfree.data.gantt.junit.SlidingGanttCategoryDatasetTests;
 import org.jfree.data.gantt.junit.TaskSeriesCollectionTests;
 import org.jfree.data.gantt.junit.TaskSeriesTests;
 import org.jfree.data.gantt.junit.TaskTests;
 import org.jfree.data.gantt.junit.XYTaskDatasetTests;
 import org.jfree.data.general.junit.DatasetGroupTests;
 import org.jfree.data.general.junit.DatasetUtilitiesTests;
 import org.jfree.data.general.junit.DefaultHeatMapDatasetTests;
 import org.jfree.data.general.junit.DefaultKeyedValueDatasetTests;
 import org.jfree.data.general.junit.DefaultKeyedValues2DDatasetTests;
 import org.jfree.data.general.junit.DefaultKeyedValuesDatasetTests;
 import org.jfree.data.general.junit.DefaultPieDatasetTests;
 import org.jfree.data.junit.ComparableObjectItemTests;
 import org.jfree.data.junit.ComparableObjectSeriesTests;
 import org.jfree.data.junit.DataUtilitiesTests;
 import org.jfree.data.junit.DefaultKeyedValueTests;
 import org.jfree.data.junit.DefaultKeyedValues2DTests;
 import org.jfree.data.junit.DefaultKeyedValuesTests;
 import org.jfree.data.junit.DomainOrderTests;
 import org.jfree.data.junit.KeyToGroupMapTests;
 import org.jfree.data.junit.KeyedObjectTests;
 import org.jfree.data.junit.KeyedObjects2DTests;
 import org.jfree.data.junit.KeyedObjectsTests;
 import org.jfree.data.junit.RangeTests;
 import org.jfree.data.junit.RangeTypeTests;
 import org.jfree.data.statistics.junit.BoxAndWhiskerCalculatorTests;
 import org.jfree.data.statistics.junit.BoxAndWhiskerItemTests;
 import org.jfree.data.statistics.junit.DefaultBoxAndWhiskerCategoryDatasetTests;
 import org.jfree.data.statistics.junit.DefaultBoxAndWhiskerXYDatasetTests;
 import org.jfree.data.statistics.junit.DefaultStatisticalCategoryDatasetTests;
 import org.jfree.data.statistics.junit.HistogramBinTests;
 import org.jfree.data.statistics.junit.HistogramDatasetTests;
 import org.jfree.data.statistics.junit.MeanAndStandardDeviationTests;
 import org.jfree.data.statistics.junit.RegressionTests;
 import org.jfree.data.statistics.junit.SimpleHistogramBinTests;
 import org.jfree.data.statistics.junit.SimpleHistogramDatasetTests;
 import org.jfree.data.statistics.junit.StatisticsTests;
 import org.jfree.data.time.junit.DateRangeTests;
 import org.jfree.data.time.junit.DayTests;
 import org.jfree.data.time.junit.FixedMillisecondTests;
 import org.jfree.data.time.junit.HourTests;
 import org.jfree.data.time.junit.MillisecondTests;
 import org.jfree.data.time.junit.MinuteTests;
 import org.jfree.data.time.junit.MonthTests;
 import org.jfree.data.time.junit.MovingAverageTests;
 import org.jfree.data.time.junit.QuarterTests;
 import org.jfree.data.time.junit.SecondTests;
 import org.jfree.data.time.junit.SimpleTimePeriodTests;
 import org.jfree.data.time.junit.TimePeriodAnchorTests;
 import org.jfree.data.time.junit.TimePeriodValueTests;
 import org.jfree.data.time.junit.TimePeriodValuesCollectionTests;
 import org.jfree.data.time.junit.TimePeriodValuesTests;
 import org.jfree.data.time.junit.TimeSeriesCollectionTests;
 import org.jfree.data.time.junit.TimeSeriesDataItemTests;
 import org.jfree.data.time.junit.TimeSeriesTests;
 import org.jfree.data.time.junit.TimeTableXYDatasetTests;
 import org.jfree.data.time.junit.WeekTests;
 import org.jfree.data.time.junit.YearTests;
 import org.jfree.data.time.ohlc.junit.OHLCItemTests;
 import org.jfree.data.time.ohlc.junit.OHLCSeriesCollectionTests;
 import org.jfree.data.time.ohlc.junit.OHLCSeriesTests;
 import org.jfree.data.time.ohlc.junit.OHLCTests;
 import org.jfree.data.xy.junit.CategoryTableXYDatasetTests;
 import org.jfree.data.xy.junit.DefaultHighLowDatasetTests;
 import org.jfree.data.xy.junit.DefaultIntervalXYDatasetTests;
 import org.jfree.data.xy.junit.DefaultOHLCDatasetTests;
 import org.jfree.data.xy.junit.DefaultTableXYDatasetTests;
 import org.jfree.data.xy.junit.DefaultWindDatasetTests;
 import org.jfree.data.xy.junit.DefaultXYDatasetTests;
 import org.jfree.data.xy.junit.DefaultXYZDatasetTests;
 import org.jfree.data.xy.junit.IntervalXYDelegateTests;
 import org.jfree.data.xy.junit.MatrixSeriesCollectionTests;
 import org.jfree.data.xy.junit.MatrixSeriesTests;
 import org.jfree.data.xy.junit.OHLCDataItemTests;
 import org.jfree.data.xy.junit.TableXYDatasetTests;
 import org.jfree.data.xy.junit.VectorDataItemTests;
 import org.jfree.data.xy.junit.VectorSeriesCollectionTests;
 import org.jfree.data.xy.junit.VectorSeriesTests;
 import org.jfree.data.xy.junit.VectorTests;
 import org.jfree.data.xy.junit.XIntervalDataItemTests;
 import org.jfree.data.xy.junit.XIntervalSeriesCollectionTests;
 import org.jfree.data.xy.junit.XIntervalSeriesTests;
 import org.jfree.data.xy.junit.XYBarDatasetTests;
 import org.jfree.data.xy.junit.XYCoordinateTests;
 import org.jfree.data.xy.junit.XYDataItemTests;
 import org.jfree.data.xy.junit.XYIntervalDataItemTests;
 import org.jfree.data.xy.junit.XYIntervalSeriesCollectionTests;
 import org.jfree.data.xy.junit.XYIntervalSeriesTests;
 import org.jfree.data.xy.junit.XYIntervalTests;
 import org.jfree.data.xy.junit.XYSeriesCollectionTests;
 import org.jfree.data.xy.junit.XYSeriesTests;
 import org.jfree.data.xy.junit.YIntervalDataItemTests;
 import org.jfree.data.xy.junit.YIntervalSeriesCollectionTests;
 import org.jfree.data.xy.junit.YIntervalSeriesTests;
 import org.jfree.data.xy.junit.YIntervalTests;
 import org.jfree.data.xy.junit.YWithXIntervalTests;
 
 public class AllTestSuitesTests extends TestCase {
 
 	public static Test suite() {
 		TestSuite suite = new TestSuite(AllTestSuitesTests.class.getName());
 		// $JUnit-BEGIN$
 
 		// AnnotationsPackageTests
 		suite.addTestSuite(CategoryLineAnnotationTests.class);
 		suite.addTestSuite(CategoryPointerAnnotationTests.class);
 		suite.addTestSuite(CategoryTextAnnotationTests.class);
 		suite.addTestSuite(TextAnnotationTests.class);
 		suite.addTestSuite(XYBoxAnnotationTests.class);
 		suite.addTestSuite(XYDrawableAnnotationTests.class);
 		suite.addTestSuite(XYImageAnnotationTests.class);
 		suite.addTestSuite(XYLineAnnotationTests.class);
 		suite.addTestSuite(XYPointerAnnotationTests.class);
 		suite.addTestSuite(XYPolygonAnnotationTests.class);
 		suite.addTestSuite(XYShapeAnnotationTests.class);
 		suite.addTestSuite(XYTextAnnotationTests.class);
 		suite.addTestSuite(XYTitleAnnotationTests.class);
 
 		// AxisPackageTests
 		suite.addTestSuite(AxisLocationTests.class);
 		suite.addTestSuite(AxisSpaceTests.class);
 		suite.addTestSuite(AxisTests.class);
 		suite.addTestSuite(CategoryAnchorTests.class);
 		suite.addTestSuite(CategoryAxisTests.class);
 		suite.addTestSuite(CategoryAxis3DTests.class);
 		suite.addTestSuite(CategoryLabelPositionTests.class);
 		suite.addTestSuite(CategoryLabelPositionsTests.class);
 		suite.addTestSuite(CategoryLabelWidthTypeTests.class);
 		suite.addTestSuite(CategoryTickTests.class);
 		suite.addTestSuite(ColorBarTests.class);
 		suite.addTestSuite(CyclicNumberAxisTests.class);
 		suite.addTestSuite(DateAxisTests.class);
 		suite.addTestSuite(DateTickTests.class);
 		suite.addTestSuite(DateTickMarkPositionTests.class);
 		suite.addTestSuite(DateTickUnitTests.class);
 		suite.addTestSuite(ExtendedCategoryAxisTests.class);
 		suite.addTestSuite(LogAxisTests.class);
 		suite.addTestSuite(LogarithmicAxisTests.class);
 		suite.addTestSuite(MarkerAxisBandTests.class);
 		suite.addTestSuite(ModuloAxisTests.class);
 		suite.addTestSuite(MonthDateFormatTests.class);
 		suite.addTestSuite(NumberAxisTests.class);
 		suite.addTestSuite(NumberAxis3DTests.class);
 		suite.addTestSuite(NumberTickUnitTests.class);
 		suite.addTestSuite(PeriodAxisTests.class);
 		suite.addTestSuite(PeriodAxisLabelInfoTests.class);
 		suite.addTestSuite(QuarterDateFormatTests.class);
 		suite.addTestSuite(SegmentedTimelineTests.class);
 		suite.addTestSuite(SegmentedTimelineTests2.class);
 		suite.addTestSuite(StandardTickUnitSourceTests.class);
 		suite.addTestSuite(SubCategoryAxisTests.class);
 		suite.addTestSuite(SymbolAxisTests.class);
 		suite.addTestSuite(TickUnitsTests.class);
 		suite.addTestSuite(ValueAxisTests.class);
 
 		// BlockPackageTests
 		suite.addTestSuite(AbstractBlockTests.class);
 		suite.addTestSuite(BlockBorderTests.class);
 		suite.addTestSuite(BlockContainerTests.class);
 		suite.addTestSuite(BorderArrangementTests.class);
 		suite.addTestSuite(ColorBlockTests.class);
 		suite.addTestSuite(ColumnArrangementTests.class);
 		suite.addTestSuite(EmptyBlockTests.class);
 		suite.addTestSuite(FlowArrangementTests.class);
 		suite.addTestSuite(GridArrangementTests.class);
 		suite.addTestSuite(LabelBlockTests.class);
 		suite.addTestSuite(LineBorderTests.class);
 		suite.addTestSuite(RectangleConstraintTests.class);
 
 		// EditorPackageTests
 		suite.addTestSuite(DefaultChartEditorTests.class);
 
 		// EncodersPackageTests
		suite.addTestSuite(KeypointPNGEncoderAdapter.class);
 
 		// EntityPackageTests
 		suite.addTestSuite(CategoryItemEntityTests.class);
 		suite.addTestSuite(CategoryLabelEntityTests.class);
 		suite.addTestSuite(ContourEntityTests.class);
 		suite.addTestSuite(LegendItemEntityTests.class);
 		suite.addTestSuite(PieSectionEntityTests.class);
 		suite.addTestSuite(StandardEntityCollectionTests.class);
 		suite.addTestSuite(TickLabelEntityTests.class);
 		suite.addTestSuite(XYItemEntityTests.class);
 
 		// ImageMapPackageTests
 		suite.addTestSuite(DynamicDriveToolTipTagFragmentGeneratorTests.class);
 		suite.addTestSuite(ImageMapUtilitiesTests.class);
 		suite.addTestSuite(OverLIBToolTipTagFragmentGeneratorTests.class);
 		suite.addTestSuite(StandardToolTipTagFragmentGeneratorTests.class);
 		suite.addTestSuite(StandardURLTagFragmentGeneratorTests.class);
 
 		// ChartPackageTests
 		suite.addTestSuite(AreaChartTests.class);
 		suite.addTestSuite(BarChartTests.class);
 		suite.addTestSuite(BarChart3DTests.class);
 		suite.addTestSuite(BoxAndWhiskerChartTests.class);
 		suite.addTestSuite(BubbleChartTests.class);
 		suite.addTestSuite(CandlestickChartTests.class);
 		suite.addTestSuite(ChartFactoryTests.class);
 		suite.addTestSuite(ChartPanelTests.class);
 		suite.addTestSuite(ChartRenderingInfoTests.class);
 		suite.addTestSuite(GanttChartTests.class);
 		suite.addTestSuite(HashUtilitiesTests.class);
 		suite.addTestSuite(HighLowChartTests.class);
 		suite.addTestSuite(HistogramChartTests.class);
 		suite.addTestSuite(JFreeChartTests.class);
 		suite.addTestSuite(LegendItemTests.class);
 		suite.addTestSuite(LegendItemCollectionTests.class);
 		suite.addTestSuite(LineChartTests.class);
 		suite.addTestSuite(LineChart3DTests.class);
 		suite.addTestSuite(MeterChartTests.class);
 		suite.addTestSuite(MouseWheelHandlerTests.class);
 		suite.addTestSuite(PaintMapTests.class);
 		suite.addTestSuite(PieChartTests.class);
 		suite.addTestSuite(PieChart3DTests.class);
 		suite.addTestSuite(PolarPlotTests.class);
 		suite.addTestSuite(ScatterPlotTests.class);
 		suite.addTestSuite(StackedAreaChartTests.class);
 		suite.addTestSuite(StackedBarChartTests.class);
 		suite.addTestSuite(StackedBarChart3DTests.class);
 		suite.addTestSuite(StackedXYAreaChartTests.class);
 		suite.addTestSuite(StandardChartThemeTests.class);
 		suite.addTestSuite(StrokeMapTests.class);
 		// suite.addTestSuite(TestUtilities.class);//No tests found
 		suite.addTestSuite(TimeSeriesChartTests.class);
 		suite.addTestSuite(WaferMapChartTests.class);
 		suite.addTestSuite(WaterfallChartTests.class);
 		suite.addTestSuite(WindPlotTests.class);
 		suite.addTestSuite(XYAreaChartTests.class);
 		suite.addTestSuite(XYBarChartTests.class);
 		suite.addTestSuite(XYLineChartTests.class);
 		suite.addTestSuite(XYStepAreaChartTests.class);
 		suite.addTestSuite(XYStepChartTests.class);
 
 		// LabelsPackageTests
 		suite.addTestSuite(BoxAndWhiskerToolTipGeneratorTests.class);
 		suite.addTestSuite(BoxAndWhiskerXYToolTipGeneratorTests.class);
 		suite.addTestSuite(BubbleXYItemLabelGeneratorTests.class);
 		suite.addTestSuite(CustomXYItemLabelGeneratorTests.class);
 		suite.addTestSuite(HighLowItemLabelGeneratorTests.class);
 		suite.addTestSuite(IntervalCategoryItemLabelGeneratorTests.class);
 		suite.addTestSuite(IntervalCategoryToolTipGeneratorTests.class);
 		suite.addTestSuite(ItemLabelAnchorTests.class);
 		suite.addTestSuite(ItemLabelPositionTests.class);
 		suite.addTestSuite(MultipleXYSeriesLabelGeneratorTests.class);
 		suite.addTestSuite(StandardCategoryItemLabelGeneratorTests.class);
 		suite.addTestSuite(StandardCategorySeriesLabelGeneratorTests.class);
 		suite.addTestSuite(StandardCategoryToolTipGeneratorTests.class);
 		suite.addTestSuite(StandardContourToolTipGeneratorTests.class);
 		suite.addTestSuite(StandardPieSectionLabelGeneratorTests.class);
 		suite.addTestSuite(StandardPieToolTipGeneratorTests.class);
 		suite.addTestSuite(StandardXYItemLabelGeneratorTests.class);
 		suite.addTestSuite(StandardXYSeriesLabelGeneratorTests.class);
 		suite.addTestSuite(StandardXYToolTipGeneratorTests.class);
 		suite.addTestSuite(StandardXYZToolTipGeneratorTests.class);
 		suite.addTestSuite(SymbolicXYItemLabelGeneratorTests.class);
 
 		// NeedlePackageTests
 		suite.addTestSuite(ArrowNeedleTests.class);
 		suite.addTestSuite(LineNeedleTests.class);
 		suite.addTestSuite(LongNeedleTests.class);
 		suite.addTestSuite(MeterNeedleTests.class);
 		suite.addTestSuite(MiddlePinNeedleTests.class);
 		suite.addTestSuite(PinNeedleTests.class);
 		suite.addTestSuite(PlumNeedleTests.class);
 		suite.addTestSuite(PointerNeedleTests.class);
 		suite.addTestSuite(ShipNeedleTests.class);
 		suite.addTestSuite(WindNeedleTests.class);
 
 		// PanelPackageTests
 		suite.addTest(CrosshairOverlayTests.suite());
 
 		// DialPackageTests
 		suite.addTestSuite(AbstractDialLayerTests.class);
 		suite.addTestSuite(DialBackgroundTests.class);
 		suite.addTestSuite(DialCapTests.class);
 		suite.addTestSuite(DialPlotTests.class);
 		suite.addTestSuite(DialPointerTests.class);
 		suite.addTestSuite(DialTextAnnotationTests.class);
 		suite.addTestSuite(DialValueIndicatorTests.class);
 		suite.addTestSuite(StandardDialFrameTests.class);
 		suite.addTestSuite(ArcDialFrameTests.class);
 		suite.addTestSuite(StandardDialRangeTests.class);
 		suite.addTestSuite(StandardDialScaleTests.class);
 
 		// PlotPackageTests
 		suite.addTestSuite(CategoryMarkerTests.class);
 		suite.addTestSuite(CategoryPlotTests.class);
 		suite.addTestSuite(ColorPaletteTests.class);
 		suite.addTestSuite(CombinedDomainCategoryPlotTests.class);
 		suite.addTestSuite(CombinedDomainXYPlotTests.class);
 		suite.addTestSuite(CombinedRangeCategoryPlotTests.class);
 		suite.addTestSuite(CombinedRangeXYPlotTests.class);
 		suite.addTestSuite(CompassPlotTests.class);
 		suite.addTestSuite(ContourPlotTests.class);
 		suite.addTestSuite(CrosshairTests.class);
 		suite.addTestSuite(DefaultDrawingSupplierTests.class);
 		suite.addTestSuite(FastScatterPlotTests.class);
 		suite.addTestSuite(IntervalMarkerTests.class);
 		suite.addTestSuite(MarkerTests.class);
 		suite.addTestSuite(MeterIntervalTests.class);
 		suite.addTestSuite(MeterPlotTests.class);
 		suite.addTestSuite(MultiplePiePlotTests.class);
 		suite.addTestSuite(PieLabelRecordTests.class);
 		suite.addTestSuite(PiePlotTests.class);
 		suite.addTestSuite(PiePlot3DTests.class);
 		suite.addTestSuite(PlotOrientationTests.class);
 		suite.addTestSuite(PlotRenderingInfoTests.class);
 		suite.addTestSuite(PlotTests.class);
 		suite.addTestSuite(PolarPlotTests.class);
 		suite.addTestSuite(RingPlotTests.class);
 		suite.addTestSuite(SpiderWebPlotTests.class);
 		suite.addTestSuite(ThermometerPlotTests.class);
 		suite.addTestSuite(ValueMarkerTests.class);
 		suite.addTestSuite(XYPlotTests.class);
 
 		// RendererCategoryPackageTests
 		suite.addTestSuite(AbstractCategoryItemRendererTests.class);
 		suite.addTestSuite(AreaRendererTests.class);
 		suite.addTestSuite(BarRendererTests.class);
 		suite.addTestSuite(BarRenderer3DTests.class);
 		suite.addTestSuite(BoxAndWhiskerRendererTests.class);
 		suite.addTestSuite(CategoryStepRendererTests.class);
 		suite.addTestSuite(DefaultCategoryItemRendererTests.class);
 		suite.addTestSuite(GanttRendererTests.class);
 		suite.addTestSuite(GradientBarPainterTests.class);
 		suite.addTestSuite(GroupedStackedBarRendererTests.class);
 		suite.addTestSuite(IntervalBarRendererTests.class);
 		suite.addTestSuite(LayeredBarRendererTests.class);
 		suite.addTestSuite(LevelRendererTests.class);
 		suite.addTestSuite(LineAndShapeRendererTests.class);
 		suite.addTestSuite(LineRenderer3DTests.class);
 		suite.addTestSuite(MinMaxCategoryRendererTests.class);
 		suite.addTestSuite(ScatterRendererTests.class);
 		suite.addTestSuite(StackedAreaRendererTests.class);
 		suite.addTestSuite(StackedBarRendererTests.class);
 		suite.addTestSuite(StackedBarRenderer3DTests.class);
 		suite.addTestSuite(StandardBarPainterTests.class);
 		suite.addTestSuite(StatisticalBarRendererTests.class);
 		suite.addTestSuite(StatisticalLineAndShapeRendererTests.class);
 		suite.addTestSuite(WaterfallBarRendererTests.class);
 
 		// RendererPackageTests
 		suite.addTestSuite(AbstractRendererTests.class);
 		suite.addTestSuite(AreaRendererEndTypeTests.class);
 		suite.addTestSuite(DefaultPolarItemRendererTests.class);
 		suite.addTestSuite(GrayPaintScaleTests.class);
 		suite.addTestSuite(LookupPaintScaleTests.class);
 		suite.addTestSuite(OutlierTests.class);
 		suite.addTestSuite(RendererUtilitiesTests.class);
 
 		// RendererXYPackageTests
 		suite.addTestSuite(AbstractXYItemRendererTests.class);
 		suite.addTestSuite(CandlestickRendererTests.class);
 		suite.addTestSuite(ClusteredXYBarRendererTests.class);
 		suite.addTestSuite(DeviationRendererTests.class);
 		suite.addTestSuite(GradientXYBarPainterTests.class);
 		suite.addTestSuite(HighLowRendererTests.class);
 		suite.addTestSuite(StackedXYAreaRendererTests.class);
 		suite.addTestSuite(StackedXYAreaRenderer2Tests.class);
 		suite.addTestSuite(StackedXYBarRendererTests.class);
 		suite.addTestSuite(StandardXYBarPainterTests.class);
 		suite.addTestSuite(StandardXYItemRendererTests.class);
 		suite.addTestSuite(VectorRendererTests.class);
 		suite.addTestSuite(WindItemRendererTests.class);
 		suite.addTestSuite(XYAreaRendererTests.class);
 		suite.addTestSuite(XYAreaRenderer2Tests.class);
 		suite.addTestSuite(XYBarRendererTests.class);
 		suite.addTestSuite(XYBlockRendererTests.class);
 		suite.addTestSuite(XYBoxAndWhiskerRendererTests.class);
 		suite.addTestSuite(XYBubbleRendererTests.class);
 		suite.addTestSuite(XYDifferenceRendererTests.class);
 		suite.addTestSuite(XYDotRendererTests.class);
 		suite.addTestSuite(XYErrorRendererTests.class);
 		suite.addTestSuite(XYLineAndShapeRendererTests.class);
 		suite.addTestSuite(XYLine3DRendererTests.class);
 		suite.addTestSuite(XYShapeRendererTests.class);
 		suite.addTestSuite(XYSplineRendererTests.class);
 		suite.addTestSuite(XYStepRendererTests.class);
 		suite.addTestSuite(XYStepAreaRendererTests.class);
 		suite.addTestSuite(YIntervalRendererTests.class);
 
 		// TitlePackageTests
 		suite.addTestSuite(CompositeTitleTests.class);
 		suite.addTestSuite(DateTitleTests.class);
 		suite.addTestSuite(ImageTitleTests.class);
 		suite.addTestSuite(LegendGraphicTests.class);
 		suite.addTestSuite(LegendTitleTests.class);
 		suite.addTestSuite(PaintScaleLegendTests.class);
 		suite.addTestSuite(ShortTextTitleTests.class);
 		suite.addTestSuite(TextTitleTests.class);
 		suite.addTestSuite(TitleTests.class);
 
 		// UrlsPackageTests
 		suite.addTestSuite(CustomCategoryURLGeneratorTests.class);
 		suite.addTestSuite(CustomPieURLGeneratorTests.class);
 		suite.addTestSuite(CustomXYURLGeneratorTests.class);
 		suite.addTestSuite(StandardCategoryURLGeneratorTests.class);
 		suite.addTestSuite(StandardPieURLGeneratorTests.class);
 		suite.addTestSuite(StandardXYURLGeneratorTests.class);
 		suite.addTestSuite(TimeSeriesURLGeneratorTests.class);
 
 		// UtilPackageTests
 		suite.addTestSuite(HexNumberFormatTests.class);
 		suite.addTestSuite(LineUtilitiesTests.class);
 		suite.addTestSuite(LogFormatTests.class);
 		suite.addTestSuite(ParamChecksTests.class);
 		suite.addTestSuite(RelativeDateFormatTests.class);
 
 		// DataCategoryPackageTests
 		suite.addTestSuite(CategoryToPieDatasetTests.class);
 		suite.addTestSuite(DefaultCategoryDatasetTests.class);
 		suite.addTestSuite(DefaultIntervalCategoryDatasetTests.class);
 		suite.addTestSuite(SlidingCategoryDatasetTests.class);
 
 		// DataFunctionPackageTests
 		suite.addTestSuite(LineFunction2DTests.class);
 		suite.addTestSuite(NormalDistributionFunction2DTests.class);
 		suite.addTestSuite(PolynomialFunction2DTests.class);
 		suite.addTestSuite(PowerFunction2DTests.class);
 
 		// DataGanttPackageTests
 		suite.addTestSuite(SlidingGanttCategoryDatasetTests.class);
 		suite.addTestSuite(TaskTests.class);
 		suite.addTestSuite(TaskSeriesTests.class);
 		suite.addTestSuite(TaskSeriesCollectionTests.class);
 		suite.addTestSuite(XYTaskDatasetTests.class);
 
 		// DataGeneralPackageTests
 		suite.addTestSuite(DatasetGroupTests.class);
 		suite.addTestSuite(DatasetUtilitiesTests.class);
 		suite.addTestSuite(DefaultHeatMapDatasetTests.class);
 		suite.addTestSuite(DefaultKeyedValueDatasetTests.class);
 		suite.addTestSuite(DefaultKeyedValuesDatasetTests.class);
 		suite.addTestSuite(DefaultKeyedValues2DDatasetTests.class);
 		suite.addTestSuite(DefaultPieDatasetTests.class);
 
 		// DataPackageTests
 		suite.addTestSuite(ComparableObjectItemTests.class);
 		suite.addTestSuite(ComparableObjectSeriesTests.class);
 		suite.addTestSuite(DataUtilitiesTests.class);
 		suite.addTestSuite(DefaultKeyedValueTests.class);
 		suite.addTestSuite(DefaultKeyedValuesTests.class);
 		suite.addTestSuite(DefaultKeyedValues2DTests.class);
 		suite.addTestSuite(DomainOrderTests.class);
 		suite.addTestSuite(KeyedObjectTests.class);
 		suite.addTestSuite(KeyedObjectsTests.class);
 		suite.addTestSuite(KeyedObjects2DTests.class);
 		suite.addTestSuite(KeyToGroupMapTests.class);
 		suite.addTestSuite(RangeTests.class);
 		suite.addTestSuite(RangeTypeTests.class);
 
 		// DataStatisticsPackageTests
 		suite.addTestSuite(BoxAndWhiskerCalculatorTests.class);
 		suite.addTestSuite(BoxAndWhiskerItemTests.class);
 		suite.addTestSuite(DefaultBoxAndWhiskerCategoryDatasetTests.class);
 		suite.addTestSuite(DefaultBoxAndWhiskerXYDatasetTests.class);
 		suite.addTestSuite(DefaultStatisticalCategoryDatasetTests.class);
 		suite.addTestSuite(HistogramBinTests.class);
 		suite.addTestSuite(HistogramDatasetTests.class);
 		suite.addTestSuite(MeanAndStandardDeviationTests.class);
 		suite.addTestSuite(RegressionTests.class);
 		suite.addTestSuite(SimpleHistogramBinTests.class);
 		suite.addTestSuite(SimpleHistogramDatasetTests.class);
 		suite.addTestSuite(StatisticsTests.class);
 
 		// DataTimePackageTests
 		suite.addTestSuite(DateRangeTests.class);
 		suite.addTestSuite(DayTests.class);
 		suite.addTestSuite(FixedMillisecondTests.class);
 		suite.addTestSuite(HourTests.class);
 		suite.addTestSuite(MinuteTests.class);
 		suite.addTestSuite(MillisecondTests.class);
 		suite.addTestSuite(MonthTests.class);
 		suite.addTestSuite(MovingAverageTests.class);
 		suite.addTestSuite(QuarterTests.class);
 		suite.addTestSuite(SecondTests.class);
 		suite.addTestSuite(SimpleTimePeriodTests.class);
 		suite.addTestSuite(TimePeriodAnchorTests.class);
 		suite.addTestSuite(TimePeriodValueTests.class);
 		suite.addTestSuite(TimePeriodValuesTests.class);
 		suite.addTestSuite(TimePeriodValuesCollectionTests.class);
 		suite.addTestSuite(TimeSeriesCollectionTests.class);
 		suite.addTestSuite(TimeSeriesTests.class);
 		suite.addTestSuite(TimeSeriesDataItemTests.class);
 		suite.addTestSuite(TimeTableXYDatasetTests.class);
 		suite.addTestSuite(WeekTests.class);
 		suite.addTestSuite(YearTests.class);
 
 		// OHLCPackageTests
 		suite.addTestSuite(OHLCItemTests.class);
 		suite.addTestSuite(OHLCSeriesCollectionTests.class);
 		suite.addTestSuite(OHLCSeriesTests.class);
 		suite.addTestSuite(OHLCTests.class);
 
 		// DataXYPackageTests
 		suite.addTestSuite(CategoryTableXYDatasetTests.class);
 		suite.addTestSuite(DefaultHighLowDatasetTests.class);
 		suite.addTestSuite(DefaultIntervalXYDatasetTests.class);
 		suite.addTestSuite(DefaultOHLCDatasetTests.class);
 		suite.addTestSuite(DefaultTableXYDatasetTests.class);
 		suite.addTestSuite(DefaultWindDatasetTests.class);
 		suite.addTestSuite(DefaultXYDatasetTests.class);
 		suite.addTestSuite(DefaultXYZDatasetTests.class);
 		suite.addTestSuite(IntervalXYDelegateTests.class);
 		suite.addTestSuite(MatrixSeriesCollectionTests.class);
 		suite.addTestSuite(MatrixSeriesTests.class);
 		suite.addTestSuite(OHLCDataItemTests.class);
 		suite.addTestSuite(TableXYDatasetTests.class);
 		suite.addTestSuite(VectorDataItemTests.class);
 		suite.addTestSuite(VectorSeriesCollectionTests.class);
 		suite.addTestSuite(VectorSeriesTests.class);
 		suite.addTestSuite(VectorTests.class);
 		suite.addTestSuite(XIntervalDataItemTests.class);
 		suite.addTestSuite(XIntervalSeriesCollectionTests.class);
 		suite.addTestSuite(XIntervalSeriesTests.class);
 		suite.addTestSuite(XYBarDatasetTests.class);
 		suite.addTestSuite(XYCoordinateTests.class);
 		suite.addTestSuite(XYDataItemTests.class);
 		suite.addTestSuite(XYIntervalDataItemTests.class);
 		suite.addTestSuite(XYIntervalSeriesCollectionTests.class);
 		suite.addTestSuite(XYIntervalSeriesTests.class);
 		suite.addTestSuite(XYIntervalTests.class);
 		suite.addTestSuite(XYSeriesCollectionTests.class);
 		suite.addTestSuite(XYSeriesTests.class);
 		suite.addTestSuite(YIntervalDataItemTests.class);
 		suite.addTestSuite(YIntervalSeriesCollectionTests.class);
 		suite.addTestSuite(YIntervalSeriesTests.class);
 		suite.addTestSuite(YIntervalTests.class);
 		suite.addTestSuite(YWithXIntervalTests.class);
 
 		// $JUnit-END$
 		return suite;
 	}
 }
