 /**
  * Language file for Frost
  *
  * This file has been created automatically.
  * Do NOT edit unless you REALLY know what you're doing!
  *
  * Language: de
  * 
  * Updated on 07-may-2004 by Rudolf Krist
  * Updated on 09-may-2004 by Michael Schierl
  * 
  */
 
 package res;
 
 import java.util.ListResourceBundle;
 
 public class LangRes_de extends ListResourceBundle {
 
 public Object[][] getContents() {
     return contents;
 }
 
 static final Object[][] contents = {
 {"*--- Enter your text after this line ---*","*--- Geben Sie Ihren Text nach dieser Zeile ein ---*"},
 {"*--- Subject line (changeable) ---*","*--- Betreffzeile (editierbar) ---*"},
 {">>> This is a Frost alternate editor message file.                <<<",">>> This is a Frost alternate editor message file.                <<<"},
 {">>> You can edit the subject and add text at the end of the file. <<<",">>> You can edit the subject and add text at the end of the file. <<<"},
 {">>> Don't change or delete the marker lines!                      <<<",">>> Don't change or delete the marker lines!                      <<<"},
 {"About","Über Frost"}, //Menü: Hilfe; anderer Vorschlag: "Info über Frost"
 {"Access rights","Zugriffsrechte"},
 {"Activate downloading","Herunterladen aktivieren"},
 {"Add attachment(s)","Ordner/Dateien anhängen"},
 {"Add Board","Forum hinzufügen"},
 {"Add Board(s)","Foren hinzufügen"},
 {"Add board(s) to list of known boards","Foren zur Liste der bekannten Foren hinzufügen"},
 {"Add Board(s) to folder","Foren zu Ordner hinzufügen"},
 {"Add new board","Neues Forum hinzufügen (erstellen)"}, //Boards -> Kontext
 {"Add new folder","Neuen Ordner hinzufügen"},
 {"Add selected board","Gewähltes Forum hinzufügen (abonnieren)"}, //Message -> Board-Attachments -> Kontext
 {"Age","Alter"},
 {"all boards","Alle Foren"},
 {"All files","Alle Dateien"},
 {"Allow 2 byte characters","2-Byte Zeichen erlauben"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
 {"Archive","Archiv"},
 {"Archive expired messages","Verfallene Nachrichten in das Archiv verschieben"},
 {"Archive Extension","Archiv-Erweiterungen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Archive folder","Archivordner"},
 {"Archives","Archive"},
 {"Attachments","Anhänge"},
 {"Audio","Audio"},
 {"Audio Extension","Audio-Erweiterungen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Automatic Indexing","Automatischer Index"},
 {"Automatic message update","Automatische Forenaktualisierung"},
 {"Automatic saving interval","Automatisches Speicherintervall (in Minuten)"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
 {"Automatic update options","Einstellungen für das automatische Aktualisieren der Foren"}, //Menü: Optionen -> Einstellungen -> Nachrichten(3)
 {"AvailableSkins","Vorhandene Skins"},
 {"Background color if updating board is selected","Hintergrundfarbe für aktualisierndes Forum (ausgewählt)"},
 {"Background color if updating board is not selected","Hintergrundfarbe für aktualisierendes Forum (nicht ausgewählt)"},
 {"Bad","BAD"},
 {"batch explanation","(größer ist schneller, kleiner ist spamsicherer)"}, //Menü: Optionen -> Einstellungen -> Hochladen
 {"Block messages with body containing (separate by ';' )","Blockiere Nachrichtentexte mit (trenne mit ';' )"},
 {"Block messages with subject containing (separate by ';' )","Blockiere Nachrichten, die im Titel folgendes enthalten (trenne mit ';' )"}, //Menü: Optionen -> Einstellungen -> Nachrichten(2)
 {"Block messages with these attached boards (separate by ';' )","Blockiere Nachrichten mit folgenden angehängten Foren (trenne mit ';' )"},
 {"block user (sets to BAD)","Nutzer blockieren (auf BAD setzen)"},
 {"Blocks","Blöcke"},
 {"board","Forum"},
 {"Board","Forum"},
 {"Board Name","Boardname"}, 
 {"Boards","Foren"},
 {"Board Information Window","Foreninformationen"},
 {"BoardInfoFrame.Board information window","Foreninformationen"},
 {"BoardInfoFrame.Boards","Foren"},
 {"BoardInfoFrame.Close","Schließen"},
 {"BoardInfoFrame.Files","Dateien"},
 {"BoardInfoFrame.Messages","Nachrichten"},
 {"BoardInfoFrame.Update","Aktualisieren"},
 {"BoardInfoFrame.Update all boards","Alle Foren aktualisieren"},
 {"BoardInfoFrame.UpdateSelectedBoardButton","Gewähltes Forum aktualisieren"},
 {"Bold","Fett"},
 {"Bold Italic","Fett Kursiv"},
 {"Browse","Durchsuchen"},
 {"Bulgarian","Bulgarisch"}, //Menü: Sprache
 {"Cancel","Abbruch"},
 {"Change destination board","Zielforum ändern"},
 {"Create new identity","Neue Indentiät anlegen"},
 {"Color","Farbe"},
 {"Content","Inhalt"},
 {"Copy keys only","CHK-Schlüssel"},
 {"Copy keys with filenames","CHK-Schlüssel und Dateiname"},
 {"Check", "CHECK"},
 {"Choose","Auswählen"},
 {"Choose a Font","Schriftart auswählen"},
 {"Choose boards","Foren auswählen"},
 {"Choose boards to attach","Foren für Anhang auswählen"},
 {"Choose file(s) / directory(s) to attach","Datei(en)/Verzeichnis(se) als Anhang auswählen"},
 {"Choose updating color of NON-SELECTED boards","Aktualisierungsfarbe für nicht selektierte Foren"},
 {"Choose updating color of SELECTED boards","Aktualisierungsfarbe für gewählte Foren"},
 {"Clean the keypool","Keypool leeren"},
 {"Close","Schließen"},
 {"Configure board","Forum konfigurieren"},
 {"Configure selected board","Gewähltes Forum konfigurieren"},
 {"Configured alternate editor line must contain a '%f' as placeholder for the filename.","Der Befehl für den alternativen Editor muß '%f' als Platzhalter für den Dateinamen enthalten"},
 {"Copy","Kopieren"},
 {"Copy extended info","erweiterte Information"},
 {"Copy to clipboard","In die Zwischenablage kopieren"},
 {"Core.init.NodeNotRunningBody","Stellen Sie sicher, daß Ihr Freenet-Knoten läuft und daß Sie Freenet richtig konfiguriert haben.\nFrost wird aber trotzdem starten, damit Sie Nachrichten lesen können.\nLassen Sie sich nicht irritieren, wenn Sie einige Fehler beim Lesen von Nachrichten bekommen ;)\n"},
 {"Core.init.NodeNotRunningTitle","Fehler - konnte keine Verbindung zum Freenet-Knoten aufbauen."},
 //{"Core.init.TransientNodeBody","Sie betreiben einen TRANSIENTEN Freenet-Knoten. Sie sollten besser auf einen PERMANENTEN Knoten umsteigen."},
 //{"Core.init.TransientNodeTitle","Transienten Knoten entdeckt"},
 {"Core.loadIdentities.ChooseName","Wählen Sie einen Namen für die Identität, er muss nicht einzigartig sein\n"},
 {"Core.loadIdentities.ConnectionNotEstablishedBody","Frost konnte keine Verbindung zu Ihre(m/n) Knoten aufbauen.\nFür den ersten Start von Frost und das Erstellen einer Identität wird eine Verbindung benötigt,\n später können Sie Frost auch ohne eine Verbindung starten.\nBitte stellen Sie sicher, daß Sie online sind und daß Freenet läuft, dann starten Sie Frost erneut."},
 {"Core.loadIdentities.ConnectionNotEstablishedTitle","Verbindung mit dem Freenet-Knoten fehlgeschlagen"},
 {"Core.loadIdentities.InvalidNameBody","Der Name darf keine '@'-Zeichen enthalten!"},
 {"Core.loadIdentities.InvalidNameTitle","Üngültige Name der Identität"},
 {"Could not start alternate editor using command: ","Kann externen Editor nicht starten: "},
 {"Create message","Erstelle Nachricht"},
 {"Cut","Ausschneiden (nicht mehr abonnieren)"}, // Board -> Kontext
 {"Cut board","Forum ausschneiden (nicht mehr abonnieren)"}, // Symbolleiste: Scheresymbol
 {"Date","Datum"},
 {"Decode each segment immediately after its download","Segmente sofort nach dem Download dekodieren"},
 {"Decoding segment","Dekodiere Segment"},
 {"Decrease Font Size","Kleinere Schrift"},
 {"Default","Default"}, // Standard? Vorgabe? fuer Sprache -> System?
 {"Delete expired messages from keypool","Verfallene Nachrichten aus dem Keypool löschen"},
 {"Delete message","Nachricht löschen"},
 {"Description","Beschreibung"},
 {"Destination","Ziel"},
 {"Development:","Entwicklung:"},
 {"Discard message","Nachricht verwerfen"},
 {"Disable all downloads","Alle Downloads deaktivieren"},
 {"Disable downloads","Herunterladen deaktivieren"}, //Menü: Optionen -> Einstellungen -> Herunterladen
 {"Disable selected downloads","Gewählte Downloads deaktivieren"},
 {"Disable splashscreen","Startlogo abschalten"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
 {"Disable uploads","Hochladen deaktivieren"}, //Menü: Optionen -> Einstellungen -> Hochladen
 {"Display","Anzeige"},
 {"Display board information window","Forumsinformationen"},
 {"Display known boards","Bekannte Foren anzeigen"},
 {"Display list of known boards","Liste bekannter Foren"},
 {"Do not trust","Nicht vertrauen"},
 {"Do spam detection","Spam-Erkennung"},
 {"Do you really want to overwrite it?","Wollen Sie sie wirklich überschreiben?"},
 {"Do you want to enter a subject?","Wollen sie einen Titel eingeben?"},
 {"Document Extension","Dokument-Erweiterungen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Documents","Dokumente"},
 {"Done","Erledigt"},
 {"Don't add boards to known boards list from users with trust states","Neue Foren von Nutzern mit folgenden Vertrauensstatus ignorieren"},
 {"Down","Runter"}, //Hauptfenster - unten
 {"Download all keys","Alle Schlüssel herunterladen"},
 {"Download attachment(s)","Attachments herunterladen"},
 {"Download directory","Herunterladen ins Verzeichnis"}, //Menü: Optionen -> Einstellungen -> Herunterladen
 {"Download selected attachment","Selektierten Anhang herunterladen"},
 {"Download selected keys","Gewählte Schlüssel herunterladen"},
 {"DownloadStatusPanel.Downloading", "Herunterladen"},
 {"Downloads","Herunterladen"}, //Menü: Optionen -> Einstellungen -> Herunterladen
 {"Dutch","Niederländisch"},
 //{"Email.address","Benachrichtigung senden an"},
 //{"Email.body","Enter the body of the email.  "<filename>" will be replaced with the name of the file"},
 {"Enable all downloads","Alle Downloads aktivieren"},
 {"Enable automatic board update","Automatische Forumaktualisierung aktivieren"},
 {"Enable downloads","Downloads aktivieren"},
 {"Enable logging","Logging aktivieren"},
 {"Enable requesting of failed download files","Fehlgeschlagene Downloads anfordern"},
 {"Enable selected downloads","Gewählte Downloads aktivieren"},
 //{"Enabled","Aktiviert"},
 {"EnableMessageBodyAA","Antialiasing für den Nachrichtenrumpf aktivieren"},
 {"EnableSkins","Skins aktivieren"},
 {"Encode requested","Kodieren angefragt"},
 {"Encoding file","Datei wird kodiert"},
 {"Encrypt for","Verschlüsseln für"},
 {"English","Englisch"},
 {"Error","Fehler"},
 {"Executable Extension","Ausführbare Erweiterungen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Executables","Ausfürhrbare Dateien"},
 {"Expiration","Verfall"},
 {"Exit","Beenden"}, //Menü: Datei
 {"Experimental Freenet Browser","Browser für Freenet (Status: experimental, sehr instabil)"}, //Menü: Plugins
 {"Failed","Fehlgeschlagen"},
 {"File","Datei"},
 {"File List","Dateiliste"},
 {"Filename","Dateiname"},
 {"Files","Dateien"},
 //{"files","Dateien"},
 {"Folder","Ordner"},
 {"folder","Ordner"},
 {"Fonts","Schriftarten"},
 {"French","Französisch"},
 {"From","Von"},
 {"Frost by Jantho","Frost von Jantho"},
 {"Frost first startup","Frost - erster Start"},
 //{"FrostSearchItemObject.*ERROR*","*ERROR*"},
 {"FrostSearchItemObject.Anonymous","Anonymous"},
 {"FrostSearchItemObject.Offline","Offline"},
 {"Generate new keypair","Neues Schlüsselpaar generieren"},
 {"German","Deutsch"},
 {"Good", "GOOD"},
 {"Help","Hilfe"},
 {"Help spread files from people marked GOOD","Leute, die als 'GOOD' markiert sind, untertützen"},
 {"help user (sets to GOOD)","Nutzer unterstützen (auf 'GOOD' setzen)"},
 {"Hide files from anonymous users","Von anonymen Nutzern hochgeladene Dateien verbergen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Hide files from people marked BAD","Dateien von mit 'BAD' markierten Leuten verbergen"},
 {"Hide messages flagged BAD","Mit 'BAD' markierte Nachrichten verbergen"},
 {"Hide messages flagged CHECK","Mit 'CHECK' markierte Nachrichten verbergen"}, //Menü: Optionen -> Einstellungen -> Nachrichten(2)
 {"Hide messages flagged OBSERVE","Mit 'OBSERVE' markierte Nachrichten verbergen"}, 
 //{"Hide messages flagged N/A","Mit N/A markierte Nachrichten verbergen"},
 {"Hide messages with trust states","Nachrichten von Nutzern mit folgenden Vertrauensstatus verbergen"},
 {"Hide unsigned messages","Unsignierte Nachrichten verbergen"}, //Menü: Optionen -> Einstellungen -> Nachrichten(2)
 {"High","High"},
 {"hours","Stunden"},
 {"Hypercube fluctuating!","Hyperwürfel fluktuiert!"},
 {"Image Extension","Bilddatei-Erweiteurungen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Images","Images"},
 {"Import existing identities.xml file","Bestehende »identities.xml« importieren"},
 {"Increase Font Size","Größere Schrift"},
 {"Index","Index"},
 {"Index file redundancy","Indexdatei-Redundanz"},
 {"Indexed attachments","Indizierte Anhänge"},
 {"Initializing Mainframe","Initialisiere das Mainframe"}, //sicher daß damit das Hauptfenster und nicht der Großrechner gemeint ist?
 {"Invert enabled state for all downloads","Enable-Status für alle Downloads invertieren"},
 {"Invert enabled state for selected downloads","Enable-Status für gewählte Downloads invertieren"},
 {"Italian","Italienisch"},
 {"Italic","Kursiv"},
 {"Japanese","Japanisch"},
 {"Keep expired messages in keypool","Verfallene Nachrichten im Keypool halten"},
 {"Key","Schlüssel"},
 {"Keyfile download HTL","Schlüsseldatei herunterladen mit HTL"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
 {"Keyfile upload HTL","Schlüsseldatei hochladen mit HTL"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
 //{"KnownBoardsFrame.Add board","Forum hinzufügen (abonnieren)"},
 {"KnownBoardsFrame.Close","Schließen"},
 {"KnownBoardsFrame.List of known boards","Liste bekannter Foren"},
 {"KnownBoardsFrame.Lookup","Suchen"},
 //{"KnownBoardsFrame.Remove board","Forum entfernen (löschen)"},
 {"KnownBoardsTableModel.Boardname","Forumname"},
 {"Language","Sprache"},
 {"Last upload","Zuletzt hochgeladen"},
 {"Less", "Weniger"},
 {"list of nodes","Durch Kommas getrennte Liste von FCP-Knoten"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
 {"list of nodes 2","(nodeA:portA, nodeB:portB, ...)"},
 {"Log file size limit (in KB)","Grenze für die Größe der Logdateien (in KB)"},
 {"Logging level","Logging Level"}, // Meldungsniveau?
 {"Low","Niedrig"},
 {"Mark ALL messages read","Alle Nachrichten als gelesen markieren"},
 {"Mark message unread","Gewählte Nachrichten als ungelesen markieren"},
 {"Maximum message display (days)","Maximale Anzahl an Tagen für angezeigte Nachrichten"},
 {"Maximum number of keys to store","Maximale Anzahl gespeicherter Schlüssel"}, //Menü: Optionen -> Einstellungen -> Verschiedenes
{"Maximum number of retries","Maximale Zahl an Einträgen"},
 {"Maximum search results","Max. Anzahl der Suchergeb."}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Medium","Medium"},
 {"Message base","Nachrichtenbasis"},
 {"Message Body","Nachrichtenrumpf"},
 {"Message download HTL","Nachrichten herunterladen mit HTL"}, //Menü: Optionen -> Einstellungen -> Nachrichten(1)
 {"Message List","Nachrichtenliste"},
 {"Message must contain board attachments", "Nachricht muß angehängte Foren haben"},
 {"Message must contain file attachments", "Nachricht muß angehängte Dateien haben"},
 {"Message upload HTL","Nachrichten hochladen mit HTL"}, //Menü: Optionen -> Einstellungen -> Nachrichten(1)
 {"Messages","Nachrichten"},
 {"Messages Today","Heutige Nachrichten"},
 {"Minimize to System Tray","In die Taskleiste minimieren"},
 {"Minimum update interval of a board","Minimales Aktualisierungsintervall eines Forums"}, //Menü: Optionen -> Einstellungen -> Nachrichten(3)
 {"minutes","Minuten"},
 {"Miscellaneous","Verschiedenes"},
 {"MoreSkinsAt","Mehr Skins gibt's hier"},
 {"More","Mehr"},
 {"Never","Niemals"},
 {"NewBoardDialog.add","Neues Forum anlegen"},
 {"NewBoardDialog.description","Beschreibung (optional). Bitte keine persönlichen Informationen angeben!"},
 {"NewBoardDialog.details","Bitte die Details des neuen Forum angeben"},
 {"NewBoardDialog.name","Name des Forum"},
 {"NewBoardDialog.title","Neues Forum anlegen"},
 {"New board","Neues Forum"},
 {"New folder","Neuer Ordner"},
 {"New Folder Name","Neuer Ordnername"},
 {"New message","Neue Nachricht"},
 {"New Node Name","Neuer Forumname"},
 {"newboard","neues Forum"},
 {"newfolder","neuer Ordner"},
 {"News","Nachrichten"},
 {"Next unread message","Nächste ungelesene Nachricht"},
 {"No boards to search into were chosed.","Keine Boards zum durchsuchen ausgewählt."},
 {"No","Nein"},
 {"No 'From' specified!","Absender fehlt!"},
 {"No subject specified!","Kein Betreff!"},
 {"No trust state is selected.", "Kein Vertrauensstatus ist gewählt!"},
 {"None (unsigned)", "NONE (unsigned)"},
 {"NoSkinsFound","Keine Skins gefunden"},
 {"Not available","Nicht vorhanden"},
 {"Number of concurrently updating boards","Gleichzeitig aktualisierte Foren"},
 {"Number of days before a message expires","Tage, bevor eine Nachricht verfällt"},
 {"Number of days to display","Anzahl dargestellter Tage"},
 {"Number of days to download backwards","Zurückliegende Tage, die gelesen werden sollen"},
 {"Number of simultaneous downloads","Gleichzeitige Downloads"},
 {"Number of simultaneous uploads","Gleichzeitige Uploads"},
 {"Number of splitfile threads","Splitfile-Threads insgesamt"}, //Menü: Optionen -> Einstellungen -> Hochladen/Runterladen
 {"Observe", "OBSERVE"},
 {"observe user (OBSERVE)","Nutzer beobachten (OBSERVE)"},
 {"Off","Aus"},
 {"OK","OK"},
 {"On","An"},
 {"Open message","Nachricht öffnen"},
 {"Open Source Project (GPL license)","Open-Source-Projekt (GPL-Lizenz)"},
 {"Options","Optionen"},
 {"Override default settings","Voreinstellungen überschreiben"},
 {"Paste","Einfügen"},
 {"Paste board","Forum einfügen"},
 {"Path","Pfad"},
 {"Pause downloading","Herunterladen anhalten"},
 {"Plain","Standard"},
 {"Please choose a new name","Einen neuen Namen aussuchen"},
 {"Please choose the version of Freenet you want to use","Bitte wählen sie die Freenet-Version"},
 {"Please enter a name for the new board","Namen für das Forum eingeben"},
 {"Please enter a name for the new folder","Namen für den Ordner eingeben"},
 {"Please enter the prefix you want to use for your files.","Dateipräfix"},
 {"Plugins","Plugins"},
 {"Preferences","Einstellungen"},
 {"Preview","Vorschau"},
 {"Private key","Privater Schlüssel"},
 {"Public board","öffentliches Forum"},
 {"Public key","öffentlicher Schlüssel"},
 {"Reaching ridiculous speed...","Lächerliche Geschwindigkeit erreicht..."},
 {"redundancy explanation","geht nicht"}, //Menü: Optionen -> Einstellungen -> Hochladen
 {"Receive duplicate messages","Doppelte Nachrichten empfangen"},
 {"Refresh","Aktualisiere"},
 {"RefreshList","Liste aktualisieren"},
 {"Reload all files","Alle Dateien hochladen"},
 {"Reload selected files","Gewählte Dateien hochladen"},
 {"Remove","Entferne (löschen)"}, //Boards -> Kontext
 {"Remove all downloads","Alle Downloads entfernen"},
 {"Remove all files","Alle Dateien entfernen"},
 {"Remove board","Forum entfernen (löschen)"},
 {"Remove finished downloads","Fertige Downloads aus Liste entfernen"},
 {"Remove finished downloads every 5 minutes","Fertige Downloads alle 5 Minuten entfernen"},
 {"Remove selected downloads","Gewählte Downloads entfernen"},
 {"Remove selected files","Gewählte Dateien entfernen"}, //UploadTabStop - ContextMenü
 {"Rename folder","Ordner umbenennen"},
 {"Reply","Antworten"},
 {"Request file after this count of retries","Datei nach folgender Anzahl von Versuchen anfordern"},
 {"Requested","Angefragt"},
 {"Requesting","beim Anfragen"},
 {"Restart failed downloads","Fehlgeschlagene Downloads wiederholen"},
 {"Restart failed uploads","Fehlgeschlagene Uploads wiederholen"},
 {"Restart selected downloads","Gewählte Downloads starten"},
 {"Restore default filenames for all files","Standarddateinamen wiederherstellen"},
 {"Restore default filenames for selected files","Standarddateinamen für gewählte Dateien wiederherstellen"},
 {"Results","Ergebnisse"},
 {"Retry","Wiederholen"}, 
 {"Retry on next startup","Beim nächsten Start wiederholen"},
 {"Sample","Sample"},
 {"Sample interval","Sample-Intervall"},
 {"Save message","Nachricht speichern"},
 {"Save message to disk","Nachricht speichern"},
 {"Search","Suchen"},
 {"Search all dates", "Suche jedes Datum"},
 {"Search all messages, no matter which trust state is set", "in allen Nachrichten suchen"},
 {"Search between dates", "Suche zwischen Datum"},
 {"Search following boards","nur gewählte Foren durchsuchen"},
 {"Search in displayed boards","in angezeigten Foren suchen"},
 {"Search in keypool and archive", "im Archiv und Keypool suchen"},
 {"Search in messages that would be displayed", "in Nachrichten suchen, die auch angezeigt werden"},
 {"Search number of days backward", "Anzahl Tage rückwärts suchen"},
 {"Search only in messages with following trust state", "nur in Nachrichten suchen mit folgenden Vertrauensstatus"},
 {"Search result","Suchergebnis"},
 {"Search messages","Nachrichten durchsuchen"},
 {"Search only in archive","nur im Archiv suchen"},
 {"Search only in keypool","nur im Keypool suchen"},
 {"Search private messages only","nur private Nachrichten durchsuchen"},
 {"Secure board","Sicheres Forum"},
 {"Select a board to view its content.","Forum auswählen, um Inhalt zu sehen."},
 {"Select a message to view its content.","Nachricht auswählen, um Inhalt zu sehen."},
 {"Select archive directory","Archivverzeichnis wählen"},
 {"Select download directory","Wähle Ordner zum Herunterladen"}, 
 {"Select files you want to upload to the","Dateien wählen, die hinzugefügt werden sollen zum"},
 {"Selected board","Gewähltes Forum"},
 {"Send message","Nachricht senden"},
 {"Sender","Absender"},
 {"Sending IP address to NSA","Sende IP-Adresse an den BND"},
 {"Set prefix for all files","Präfix für alle Dateien setzen"},
 {"Set prefix for selected files","Präfix für selektierte Dateien"},
 {"Set to","Set to"},
 {"Set to CHECK","Mit 'CHECK' markieren"},
 {"set to neutral (CHECK)","Nutzer auf neutral setzen (CHECK)"},
 {"Settings for board","Einstellungen für das Forum"},
 {"Share Downloads","Downloads freigeben"}, // Downloads freigeben?
 {"Should file attachments be added to upload table?","Anhänge in die Uploadliste eintragen?"},
 {"Show board update visualization","Aktualisierungsinformationen von Foren anzeigen"},
 {"Show deleted messages","Gelöschte Nachrichten anzeigen"},
 {"Show healing information","Heilungsinfos anzeigen"},
 {"Show memory monitor","Speichermonitor anzeigen"},
 {"Show systray icon","Taskleistenicon anzeigen"},
 {"Sig","Sig"},
 {"Sign","Signieren"},
 {"Sign shared files","Angebotene Dateien signieren"},
 {"Signature","Signatur"},
 {"Silently retry failed messages","Schweigend fehlgeschlagene Nachrichten wiederholen"},
 {"Size","Größe"},
 //{"SMTP.password","password"},
 //{"SMTP.server","server address"},
 //{"SMTP.username","username"},
 {"Sort folder","Ordner sortieren"}, //Kontext Ordner
 {"Source","Quelle"},
 {"Spanish","Spanisch"},
 {"StatusPanel.file", "Datei"},
 {"StatusPanel.files", "Dateien"},
 {"Stop search","Suche abbrechen"},
 {"Russian","Russisch"},
 {"splitfile explanation","(mehr ist besser, braucht aber auch Leistung)"}, //Menü: Optionen -> Einstellungen -> Hochladen
 {"Start encoding of selected files","Gewählte Dateien kodieren"},
 {"State","Status"}, // Zustand?
 {"Status","Status"},
 {"Subject","Betreff"},
 {"Tampered", "FAKE"},
 {"This will not delete messages","Dadurch werden keine Nachrichten gelöscht"}, //Popup?
 {"Threshold of blocked messages","Grenzwert für blockierte Nachrichten"},
 {"TOFDO","TOFDO"},
 {"TOFUP","TOFUP"},
 {"Translate Frost into another language","Frost in eine andere Sprache übersetzen"},
 {"Tries","Versuche"}, // ??
 {"Trust","Vertrauen"},
 {"Trust state","Vertrauensstatus"},
 {"Try to download all segments, even if one fails","Versuche alle Segmente runterzuladen, auch wenn eines fehlschlägt"},
 {"Trying","Versuche"}, // ?? Status beim Hoch-/Herunterladen
 {"Undelete message","Rückgängig: Nachricht löschen"},
 {"Unknown","Unbekannt"},
 {"Up","Hoch"}, //Hauptfenster - unten
 {"up htl explanation","(größer ist zuverlässiger, aber langsamer)"},
 {"Update","Aktualisieren"},
 {"Upload all files","Alle Dateien hochladen"},
 {"Upload batch size","Upload-Batch-Größe"},
 {"Upload HTL","Hochladen mit HTL"}, //Menü: Optionen -> Einstellungen -> Hochladen
 {"Upload selected files","Gewählte Dateien hochladen"},
 {"Uploading","beim Hochladen"}, //?
 {"Uploads","Hochladen"}, //Menü: Optionen -> Einstellungen -> Hochladen
 {"UploadStatusPanel.Uploading", "Hochladen"},
 {"UploadsUnderway.body","Einige Nachrichten werden gerade hochgeladen.\nWollen Sie trotzdem beenden?"},
 {"UploadsUnderway.title","Aktive Nachrichtenuploads"},
 {"Use default","Voreinstellung benutzen"}, //?
 {"Use editor for writing messages","Editor zum Verfassen von Nachrichten verwenden"},
 {"Version","Version"},
 {"Very high","Sehr hoch"}, //?
 {"Very low","Sehr niedrig"}, //?
 {"Video","Video"},
 {"Video Extension","Video-Erweiterungen"}, //Menü: Optionen -> Einstellungen -> Suchen
 {"Waiting","Warte"},
 {"Waittime after each try","Wartezeit nach jedem Versuch"},
 {"Warning","Warnung"}, //?
 {"Wasting more time","Noch mehr Zeit verschwenden"}, //Startlogo
 {"Welcome message","LESEN!\n\nNa toll, jetzt hab ich den Text vergessen."},
 {"Windows Installer:","Windows Installer:"},
 {"Yes","Ja"}, //Popup?
 {"You already have a board with name","Sie haben schon ein Forum namens"},
 {"You can create a new identity or import an existing identities.xml file","Sie können eine neue Indendität anlegen oder eine bestehende importieren"},
 {"You must enter a sender name!","Absender eingeben!"},
 {"You must enter a subject!","Betreff angeben!"}, //Popup?
 };
 }
