 /*
 	Copyright (c) 2013 The Demigods Team
 	
 	Demigods License v1
 	
 	This plugin is provided "as is" and without any warranty.  Any express or
 	implied warranties, including, but not limited to, the implied warranties
 	of merchantability and fitness for a particular purpose are disclaimed.
 	In no event shall the authors be liable to any party for any direct,
 	indirect, incidental, special, exemplary, or consequential damages arising
 	in any way out of the use or misuse of this plugin.
 	
 	Definitions
 	
 	 1. This Plugin is defined as all of the files within any archive
 	    file or any group of files released in conjunction by the Demigods Team,
 	    the Demigods Team, or a derived or modified work based on such files.
 	
 	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
 	    it with one or more Modification applied to it, or as any program that
 	    depends on this Plugin.
 	
 	 3. Distribution is defined as allowing one or more other people to in
 	    any way download or receive a copy of this Plugin, a Modified
 	    Plugin, or a derivative of this Plugin.
 	
 	 4. The Software is defined as an installed copy of this Plugin, a
 	    Modified Plugin, or a derivative of this Plugin.
 	
 	 5. The Demigods Team is defined as Alex Bennett and Alexander Chauncey
 	    of http://www.censoredsoftware.com/.
 	
 	Agreement
 	
 	 1. Permission is hereby granted to use, copy, modify and/or
 	    distribute this Plugin, provided that:
 	
 	    a. All copyright notices within source files and as generated by
 	       the Software as output are retained, unchanged.
 	
 	    b. Any Distribution of this Plugin, whether as a Modified Plugin
 	       or not, includes this license and is released under the terms
 	       of this Agreement. This clause is not dependant upon any
 	       measure of changes made to this Plugin.
 	
 	    c. This Plugin, Modified Plugins, and derivative works may not
 	       be sold or released under any paid license without explicit 
 	       permission from the Demigods Team. Copying fees for the 
 	       transport of this Plugin, support fees for installation or
 	       other services, and hosting fees for hosting the Software may,
 	       however, be imposed.
 	
 	    d. Any Distribution of this Plugin, whether as a Modified
 	       Plugin or not, requires express written consent from the
 	       Demigods Team.
 	
 	 2. You may make Modifications to this Plugin or a derivative of it,
 	    and distribute your Modifications in a form that is separate from
 	    the Plugin. The following restrictions apply to this type of
 	    Modification:
 	
 	    a. A Modification must not alter or remove any copyright notices
 	       in the Software or Plugin, generated or otherwise.
 	
 	    b. When a Modification to the Plugin is released, a
 	       non-exclusive royalty-free right is granted to the Demigods Team
 	       to distribute the Modification in future versions of the
 	       Plugin provided such versions remain available under the
 	       terms of this Agreement in addition to any other license(s) of
 	       the initial developer.
 	
 	    c. Any Distribution of a Modified Plugin or derivative requires
 	       express written consent from the Demigods Team.
 	
 	 3. Permission is hereby also granted to distribute programs which
 	    depend on this Plugin, provided that you do not distribute any
 	    Modified Plugin without express written consent.
 	
 	 4. The Demigods Team reserves the right to change the terms of this
 	    Agreement at any time, although those changes are not retroactive
 	    to past releases, unless redefining the Demigods Team. Failure to
 	    receive notification of a change does not make those changes invalid.
 	    A current copy of this Agreement can be found included with the Plugin.
 	
 	 5. This Agreement will terminate automatically if you fail to comply
 	    with the limitations described herein. Upon termination, you must
 	    destroy all copies of this Plugin, the Software, and any
 	    derivatives within 48 hours.
  */
 
 package com.censoredsoftware.Demigods.Listeners;
 
 import java.util.ArrayList;
 
 import org.bukkit.ChatColor;
 import org.bukkit.entity.*;
 import org.bukkit.event.EventHandler;
 import org.bukkit.event.EventPriority;
 import org.bukkit.event.Listener;
 import org.bukkit.event.entity.EntityDamageByEntityEvent;
 import org.bukkit.event.entity.EntityDamageEvent;
 import org.bukkit.event.entity.EntityDeathEvent;
 
 import com.censoredsoftware.Demigods.Demigods;
 import com.censoredsoftware.Demigods.Events.Battle.BattleCombineEvent;
 import com.censoredsoftware.Demigods.Events.Battle.BattleParticipateEvent;
 import com.censoredsoftware.Demigods.Events.Battle.BattleStartEvent;
 import com.censoredsoftware.Demigods.Libraries.Objects.Battle;
 import com.censoredsoftware.Demigods.Libraries.Objects.PlayerCharacter;
 import com.censoredsoftware.Demigods.Libraries.Objects.SerialLocation;
 
 public class DEntityListener implements Listener
 {
 	public static final Demigods API = Demigods.INSTANCE;
 
 	@EventHandler(priority = EventPriority.MONITOR)
 	public static void damageEvent(EntityDamageEvent event)
 	{
 		// Define variables
 		LivingEntity entity;
 		if(event.getEntityType().equals(EntityType.PLAYER)) // If it's a player
 		{
 			// Define entity as player and other variables
 			entity = (LivingEntity) event.getEntity();
 
 			// NO DAMAGE IN NO PVP ZONES FOR PLAYERS
 			if(!API.zone.canTarget(entity))
 			{
 				event.setCancelled(true);
 			}
 		}
 	}
 
 	@EventHandler(priority = EventPriority.MONITOR)
 	public static void damageByEntityEvent(EntityDamageByEntityEvent event)
 	{
 		Entity attacked = event.getEntity();
 		Entity attacker = event.getDamager();
 
 		if(attacker instanceof Player)
 		{
 			Player hitting = (Player) attacker;
 
 			// NO PVP
 			if(!API.zone.canTarget(attacked))
 			{
 				hitting.sendMessage(ChatColor.GRAY + "No-PVP in this zone.");
 				event.setCancelled(true);
 				return;
 			}
 
 			if(attacked instanceof Villager) // If it's a villager
 			{
 				// Define villager
 				Villager villager = (Villager) attacked;
 
 				// Define attacker and name
 				if(event.getDamage() > villager.getHealth()) hitting.sendMessage(ChatColor.GRAY + "One weaker than you has been slain by your hand.");
 			}
 			else if(attacked instanceof Player) // If it's a player
 			{
 				// Define player
 				Player hit = (Player) attacked;
 
 				Battle battle = null;
 				Battle otherBattle = null;
 				PlayerCharacter hitChar = API.player.getCurrentChar(hit);
 				PlayerCharacter hittingChar = API.player.getCurrentChar(hitting);
 
 				if(API.battle.isInAnyActiveBattle(hitChar))
 				{
 					battle = API.battle.getActiveBattle(hitChar);
 					if(API.battle.isInAnyActiveBattle(hittingChar) && API.battle.getActiveBattle(hittingChar) != battle) otherBattle = API.battle.getActiveBattle(hittingChar);
 				}
 				else if(API.battle.isInAnyActiveBattle(hittingChar))
 				{
 					battle = API.battle.getActiveBattle(hittingChar);
 					if(API.battle.isInAnyActiveBattle(hitChar) && API.battle.getActiveBattle(hitChar) != battle) otherBattle = API.battle.getActiveBattle(hitChar);
 				}
 				else if(API.battle.isNearAnyActiveBattle(hit.getLocation()))
 				{
 					battle = API.battle.getActiveBattle(hit.getLocation());
 					if(API.battle.isNearAnyActiveBattle(hitting.getLocation()) && API.battle.getActiveBattle(hitting.getLocation()) != battle) otherBattle = API.battle.getActiveBattle(hitting.getLocation());
 				}
 				else if(API.battle.isNearAnyActiveBattle(hitting.getLocation()))
 				{
 					battle = API.battle.getActiveBattle(hitting.getLocation());
 					if(API.battle.isNearAnyActiveBattle(hit.getLocation()) && API.battle.getActiveBattle(hit.getLocation()) != battle) otherBattle = API.battle.getActiveBattle(hit.getLocation());
 				}
 
 				if(battle == null)
 				{
 					Long startTime = System.currentTimeMillis();
 					int battleID = API.object.generateInt(5);
 					BattleStartEvent battleEvent = new BattleStartEvent(battleID, hitChar, hittingChar, startTime);
 					API.misc.callEvent(battleEvent);
 					if(!battleEvent.isCancelled()) battle = new Battle(hittingChar, hitChar, startTime, battleID);
 				}
 				else
 				{
 					if(otherBattle == null)
 					{
 						int battleID = battle.getID();
 						BattleParticipateEvent battleEvent = new BattleParticipateEvent(battleID, hitChar, hittingChar);
 						API.misc.callEvent(battleEvent);
 						if(!battleEvent.isCancelled())
 						{
 							battle.addCharacter(hitChar);
 							battle.addCharacter(hittingChar);
 							API.data.saveTimedData(battleID, "battle_active", true, 10);
 						}
 					}
 					else
 					{
 						// Set other battles to inactive
 						battle.setActive(false);
 						otherBattle.setActive(false);
 
 						BattleCombineEvent battleEvent = null;
 						int battleID = API.object.generateInt(5);
 						Battle combinedBattle = null;
 						if(battle.getStartTime() < otherBattle.getStartTime())
 						{
 							battleEvent = new BattleCombineEvent(battleID, battle, otherBattle, System.currentTimeMillis());
 							API.misc.callEvent(battleEvent);
 							if(!battleEvent.isCancelled())
 							{
 								combinedBattle = new Battle(API.character.getChar(battle.getWhoStarted()), hitChar, battle.getStartTime(), battleID);
 								combinedBattle.addCharacter(hittingChar);
 							}
 							else return;
 						}
 						else
 						{
 							battleEvent = new BattleCombineEvent(battleID, otherBattle, battle, System.currentTimeMillis());
 							API.misc.callEvent(battleEvent);
 							if(!battleEvent.isCancelled())
 							{
 								combinedBattle = new Battle(API.character.getChar(otherBattle.getWhoStarted()), hitChar, otherBattle.getStartTime(), battleID);
 								combinedBattle.addCharacter(hittingChar);
 							}
 							else return;
 						}
 
 						// Add all involved locations and characters from both other events
 						ArrayList<Integer> charIDs = new ArrayList<Integer>();
 						ArrayList<SerialLocation> locations = new ArrayList<SerialLocation>();
 
 						// Battle
 						for(int charID : battle.getCharIDs())
 						{
 							if(!charIDs.contains(charID)) charIDs.add(charID);
 						}
 						for(SerialLocation location : battle.getLocations())
 						{
 							if(!locations.contains(location)) locations.add(location);
 						}
 
 						// Other Battle
 						for(int charID : otherBattle.getCharIDs())
 						{
 							if(!charIDs.contains(charID)) charIDs.add(charID);
 						}
 						for(SerialLocation location : otherBattle.getLocations())
 						{
 							if(!locations.contains(location)) locations.add(location);
 						}
 
 						// Overwrite data in the new combined battle
 						combinedBattle.overwriteCharIDs(charIDs);
 						combinedBattle.overwriteLocations(locations);
 					}
 				}
 			}
 		}
 	}
 
 	@EventHandler(priority = EventPriority.HIGHEST)
 	public static void entityDeath(EntityDeathEvent event)
 	{
 		if(event.getEntityType().equals(EntityType.PLAYER))
 		{
 			// Define variables
 			Player player = (Player) event.getEntity();
 			PlayerCharacter character = API.player.getCurrentChar(player);
            if(character == null) return;
 			String deity = API.object.capitalize(character.getDeity());
 			int devotion = character.getDevotion();
 			int devotionRemoved = (int) Math.ceil(devotion * .19);
 
 			// Set their devotion and add a death
 			character.subtractDevotion(devotionRemoved);
 			API.player.addDeath(player);
 
 			// Let 'em know
 			player.sendMessage(ChatColor.RED + "You have failed " + deity + "!");
 			player.sendMessage(ChatColor.RED + "You have been stripped of " + devotionRemoved + " devotion!");
 		}
 	}
 
 }
