 package aigilas;
 
 public class Common {
 
     public static final String Altar = "Altar";
     public static final String Back = "Back";
     public static final String Base_Skill_Effect = "Base_Skill_Effect";
     public static final String Breaking_Wheel = "Breaking_Wheel";
     public static final String Cancel = "Cancel";
     public static final String Confirm = "Confirm";
     public static final String Creature = "Creature";
     public static final String CycleLeft = "Cycle_Left";
     public static final String CycleRight = "Cycle_Right";
     public static final String Downstairs = "Downstairs";
     public static final String Dummy = "Dummy";
     public static final String Envy = "Envy";
     public static final String Envy_Acolyte = "Envy_Acolyte";
     public static final String Free = "Free";
     public static final String Gluttony = "Gluttony";
     public static final String Gluttony_Acolyte = "Gluttony_Acolyte";
     public static final String Greed = "Greed";
     public static final String Greed_Acolyte = "Greed_Acolyte";
     public static final String Hand = "Hand";
     public static final String Hot_Skill_1 = "Hot_Skill_1";
     public static final String Hot_Skill_2 = "Hot_Skill_2";
     public static final String Hot_Skill_3 = "Hot_Skill_3";
     public static final String Hud_BG = "Hud_BG";
     public static final String Inventory = "Inventory";
     public static final String Item = "Item";
     public static final String LockSkill = "Lock_Skill";
     public static final String Lust = "Lust";
     public static final String Lust_Acolyte = "Lust_Acolyte";
     public static final String Minion = "Minion";
     public static final String MoveDown = "Move_Down";
     public static final String MoveLeft = "Move_Left";
     public static final String MoveRight = "Move_Right";
     public static final String MoveUp = "Move_Up";
     public static final String Peon = "Peon";
     public static final String Pride = "Pride";
     public static final String Pride_Acolyte = "Pride_Acolyte";
     public static final String Serpent = "Serpent";
     public static final String Skill = "Skill";
     public static final String Skill_Effect = "Skill_Effect";
     public static final String Sloth = "Sloth";
     public static final String Sloth_Acolyte = "Sloth_Acolyte";
     public static final String Stairs = "Stairs";
     public static final String Start = "Start";
     public static final String ToggleDevConsole = "Toggle_Dev_Console";
     public static final String Upstairs = "Upstairs";
     public static final String Wall = "Wall";
     public static final String Wrath = "Wrath";
     public static final String Wrath_Acolyte = "Wrath_Acolyte";
     public static final String Zorb = "Zorb";
     public static final String Combo_Marker = "Combo_Marker";
 }
