 /*
  * AddMedewerker.java
  *
  * Created on 19-jan-2011, 23:20:39
  */
 
 package view;
 
 import connectivity.ShaEncrypt;
 import model.Employee;
 import roosterprogramma.RoosterProgramma;
 
 /**
  *
  * @author Dymion
  */
 public class ChAddEmployee extends javax.swing.JPanel {
 
     private Employee employee;
     private boolean isAdd = true;
 
     /** Creates new form AddMedewerker */
     public ChAddEmployee() {
         initComponents();
         lblNameInUse.setVisible(false);
         lblNumberInUse.setVisible(false);
     }
 
     public ChAddEmployee(Employee employee) {
         this.employee = employee;
         this.isAdd = false;
         initComponents();
         fillFields();
         lblNameInUse.setVisible(false);
         lblNumberInUse.setVisible(false);
     }
 
     private void fillFields() {
         tfEmployeeNumber.setText(Integer.toString(employee.getEmployeeNumber()));
         tfFirstName.setText(employee.getFirstName());
         tfFamilyName.setText(employee.getFamilyName());
         cbFullTime.setSelected(employee.isFullTime());
         cbClerk.setSelected(employee.isClerk());
         if (employee.isPartTime())
         {
             cbPartTime.setSelected(true);
             pnlPartTime.setVisible(true);
             pnlCallWorker.setVisible(false);
             tfAmountHours.setText(Double.toString(employee.getContractHours()));
         }
         else if(employee.isCallWorker())
         {
             cbCallWorker.setSelected(true);
             pnlCallWorker.setVisible(true);
             pnlPartTime.setVisible(false);
             tfMinAmountHours.setText(Double.toString(employee.getContractHours()));
         }
         else
         {
             pnlPartTime.setVisible(false);
             pnlCallWorker.setVisible(false);
         }
     }
 
     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
 
         buttonGroup = new javax.swing.ButtonGroup();
         lblEmployeeNumber = new javax.swing.JLabel();
         lblFirstName = new javax.swing.JLabel();
         lblFamilyName = new javax.swing.JLabel();
         lblWachtwoord = new javax.swing.JLabel();
         lblFullTime = new javax.swing.JLabel();
         lblPartTime = new javax.swing.JLabel();
         lblCallWorker = new javax.swing.JLabel();
         tfEmployeeNumber = new javax.swing.JTextField();
         tfFirstName = new javax.swing.JTextField();
         tfFamilyName = new javax.swing.JTextField();
         cbFullTime = new javax.swing.JCheckBox();
         cbPartTime = new javax.swing.JCheckBox();
         cbCallWorker = new javax.swing.JCheckBox();
         btnCancel = new javax.swing.JButton();
         btnSave = new javax.swing.JButton();
         tfPassword = new javax.swing.JPasswordField();
         lblNameInUse = new javax.swing.JLabel();
         lblNumberInUse = new javax.swing.JLabel();
         pnlPartTime = new javax.swing.JPanel();
         lblAmountHours = new javax.swing.JLabel();
         tfAmountHours = new javax.swing.JTextField();
         pnlCallWorker = new javax.swing.JPanel();
         lblMinAmountHours = new javax.swing.JLabel();
         tfMinAmountHours = new javax.swing.JTextField();
         jLabel1 = new javax.swing.JLabel();
         cbClerk = new javax.swing.JCheckBox();
 
         lblEmployeeNumber.setText("PersoneelsNummer:");
 
         lblFirstName.setText("Voornaam:");
 
         lblFamilyName.setText("Achternaam:");
 
         lblWachtwoord.setText("Wachtwoord:");
 
         lblFullTime.setText("Fulltime:");
 
         lblPartTime.setText("Parttime:");
 
         lblCallWorker.setText("Oproepkracht:");
 
         tfEmployeeNumber.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyReleased(java.awt.event.KeyEvent evt) {
                 tfEmployeeNumberKeyReleased(evt);
             }
         });
 
         tfFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyReleased(java.awt.event.KeyEvent evt) {
                 tfFirstNameKeyReleased(evt);
             }
         });
 
         tfFamilyName.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyReleased(java.awt.event.KeyEvent evt) {
                 tfFamilyNameKeyReleased(evt);
             }
         });
 
         buttonGroup.add(cbFullTime);
         cbFullTime.setSelected(true);
         cbFullTime.addChangeListener(new javax.swing.event.ChangeListener() {
             public void stateChanged(javax.swing.event.ChangeEvent evt) {
                 cbFullTimeStateChanged(evt);
             }
         });
 
         buttonGroup.add(cbPartTime);
         cbPartTime.addChangeListener(new javax.swing.event.ChangeListener() {
             public void stateChanged(javax.swing.event.ChangeEvent evt) {
                 cbPartTimeStateChanged(evt);
             }
         });
 
         buttonGroup.add(cbCallWorker);
         cbCallWorker.addChangeListener(new javax.swing.event.ChangeListener() {
             public void stateChanged(javax.swing.event.ChangeEvent evt) {
                 cbCallWorkerStateChanged(evt);
             }
         });
 
         btnCancel.setText("Annuleren");
         btnCancel.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 btnCancelActionPerformed(evt);
             }
         });
 
         btnSave.setText("Opslaan");
         btnSave.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 btnSaveActionPerformed(evt);
             }
         });
 
         tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyReleased(java.awt.event.KeyEvent evt) {
                 tfPasswordKeyReleased(evt);
             }
         });
 
         lblNameInUse.setText("De combinatie voor- en achternaam is al in gebruik!");
 
         lblNumberInUse.setText("Dat nummer is al in gebruik!");
 
         lblAmountHours.setText("Aantal uur per week:");
 
         tfAmountHours.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyReleased(java.awt.event.KeyEvent evt) {
                 tfAmountHoursKeyReleased(evt);
             }
         });
 
         javax.swing.GroupLayout pnlPartTimeLayout = new javax.swing.GroupLayout(pnlPartTime);
         pnlPartTime.setLayout(pnlPartTimeLayout);
         pnlPartTimeLayout.setHorizontalGroup(
             pnlPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPartTimeLayout.createSequentialGroup()
                 .addComponent(lblAmountHours, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                 .addGap(18, 18, 18)
                 .addComponent(tfAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap())
         );
         pnlPartTimeLayout.setVerticalGroup(
             pnlPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(pnlPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(lblAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addComponent(tfAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         );
 
         lblMinAmountHours.setText("Minimum aantal uur per week:");
 
         tfMinAmountHours.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyReleased(java.awt.event.KeyEvent evt) {
                 tfMinAmountHoursKeyReleased(evt);
             }
         });
 
         javax.swing.GroupLayout pnlCallWorkerLayout = new javax.swing.GroupLayout(pnlCallWorker);
         pnlCallWorker.setLayout(pnlCallWorkerLayout);
         pnlCallWorkerLayout.setHorizontalGroup(
             pnlCallWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(pnlCallWorkerLayout.createSequentialGroup()
                 .addComponent(lblMinAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(18, 18, 18)
                 .addComponent(tfMinAmountHours, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                 .addContainerGap())
         );
         pnlCallWorkerLayout.setVerticalGroup(
             pnlCallWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(pnlCallWorkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                 .addComponent(lblMinAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addComponent(tfMinAmountHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         );
 
         jLabel1.setText("Baliemedewerker:");
 
         buttonGroup.add(cbClerk);
         cbClerk.addChangeListener(new javax.swing.event.ChangeListener() {
             public void stateChanged(javax.swing.event.ChangeEvent evt) {
                 cbClerkStateChanged(evt);
             }
         });
 
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         this.setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(btnCancel)
                             .addGroup(layout.createSequentialGroup()
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(lblPartTime)
                                     .addComponent(lblEmployeeNumber)
                                     .addComponent(lblFirstName)
                                     .addComponent(lblFamilyName)
                                     .addComponent(lblWachtwoord)
                                     .addComponent(lblFullTime)
                                     .addComponent(lblCallWorker))
                                 .addGap(14, 14, 14)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addGroup(layout.createSequentialGroup()
                                         .addGap(4, 4, 4)
                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                             .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(tfFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(tfEmployeeNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                             .addComponent(tfFamilyName, javax.swing.GroupLayout.Alignment.LEADING))
                                         .addGap(18, 18, 18)
                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(lblNumberInUse)
                                             .addComponent(lblNameInUse)))
                                     .addGroup(layout.createSequentialGroup()
                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(cbCallWorker)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addComponent(cbFullTime)
                                                 .addComponent(cbPartTime))
                                             .addComponent(cbClerk))
                                         .addGap(18, 18, 18)
                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(pnlPartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                             .addComponent(pnlCallWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                         .addComponent(btnSave))
                     .addComponent(jLabel1))
                 .addContainerGap())
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(lblEmployeeNumber)
                     .addComponent(tfEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(lblNumberInUse))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(lblFirstName)
                     .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(lblFamilyName)
                     .addComponent(tfFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(lblNameInUse))
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGap(18, 18, 18)
                         .addComponent(lblWachtwoord))
                     .addGroup(layout.createSequentialGroup()
                         .addGap(12, 12, 12)
                         .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                 .addGap(25, 25, 25)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                         .addComponent(lblFullTime)
                         .addGap(25, 25, 25)
                         .addComponent(lblPartTime))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                         .addComponent(cbFullTime)
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(pnlPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                             .addComponent(cbPartTime))))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(pnlCallWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                             .addComponent(cbCallWorker)
                             .addComponent(lblCallWorker))
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                             .addComponent(jLabel1)
                             .addComponent(cbClerk))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(btnCancel)
                             .addComponent(btnSave))))
                 .addContainerGap())
         );
     }// </editor-fold>//GEN-END:initComponents
 
     private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         RoosterProgramma.getInstance().showPanel(new EmployeeOverview());
     }//GEN-LAST:event_btnCancelActionPerformed
 
     private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         int employeeNumber = Integer.parseInt(tfEmployeeNumber.getText());
         String firstName = tfFirstName.getText();
         String familyName = tfFamilyName.getText();
         String password = RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword());
         boolean fullTime = cbFullTime.isSelected();
         boolean partTime = cbPartTime.isSelected();
         boolean callWorker = cbCallWorker.isSelected();
         boolean clerk = cbClerk.isSelected();
 
         if (isAdd)
         {
             Employee newEmployee = new Employee();
             newEmployee.setEmployeeNumber(employeeNumber);
             newEmployee.setFirstName(firstName);
             newEmployee.setFamilyName(familyName);
             newEmployee.setPassword(ShaEncrypt.SHA1(password));
             newEmployee.setFullTime(fullTime);
             newEmployee.setPartTime(partTime);
             newEmployee.setCallWorker(callWorker);
             newEmployee.setClerk(clerk);
             if (newEmployee.isCallWorker())
             {
                 newEmployee.setContractHours(Double.parseDouble(tfMinAmountHours.getText()));
             }
             else if (newEmployee.isPartTime())
             {
                 newEmployee.setContractHours(Double.parseDouble(tfAmountHours.getText()));
             }
             else if (newEmployee.isFullTime())
             {
                 newEmployee.setContractHours(40);
             }
             RoosterProgramma.getQueryManager().addEmployee(newEmployee);
         }
         else
         {
             employee.setFirstName(firstName);
             employee.setFamilyName(familyName);
             employee.setPassword(ShaEncrypt.SHA1(password));
             employee.setFullTime(fullTime);
             employee.setPartTime(partTime);
             employee.setCallWorker(callWorker);
             employee.setClerk(clerk);
             if (employee.isCallWorker())
             {
                 employee.setContractHours(Double.parseDouble(tfMinAmountHours.getText()));
             }
             else if (employee.isPartTime())
             {
                 employee.setContractHours(Double.parseDouble(tfAmountHours.getText()));
             }
             else if (employee.isFullTime())
             {
                 employee.setContractHours(40);
             }
             RoosterProgramma.getQueryManager().changeEmployee(employee);
         }
         RoosterProgramma.getInstance().showPanel(new EmployeeSelect());
         
     }//GEN-LAST:event_btnSaveActionPerformed
 
     private void tfEmployeeNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmployeeNumberKeyReleased
         checkEnabled();
     }//GEN-LAST:event_tfEmployeeNumberKeyReleased
 
     private void tfFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstNameKeyReleased
         checkEnabled();
     }//GEN-LAST:event_tfFirstNameKeyReleased
 
     private void tfFamilyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFamilyNameKeyReleased
         checkEnabled();
     }//GEN-LAST:event_tfFamilyNameKeyReleased
 
     private void tfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyReleased
         checkEnabled();
     }//GEN-LAST:event_tfPasswordKeyReleased
 
     private void cbFullTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbFullTimeStateChanged
         checkEnabled();
     }//GEN-LAST:event_cbFullTimeStateChanged
 
     private void cbPartTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPartTimeStateChanged
         checkEnabled();
         if (cbPartTime.isSelected())
         {
             pnlPartTime.setVisible(true);
         }
         else
         {
             pnlPartTime.setVisible(false);
         }
     }//GEN-LAST:event_cbPartTimeStateChanged
 
     private void cbCallWorkerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCallWorkerStateChanged
         checkEnabled();
         if (cbCallWorker.isSelected())
         {
             pnlCallWorker.setVisible(true);
         }
         else
         {
             pnlCallWorker.setVisible(false);
         }
     }//GEN-LAST:event_cbCallWorkerStateChanged
 
     private void tfAmountHoursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAmountHoursKeyReleased
         checkEnabled();
     }//GEN-LAST:event_tfAmountHoursKeyReleased
 
     private void tfMinAmountHoursKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMinAmountHoursKeyReleased
         checkEnabled();
     }//GEN-LAST:event_tfMinAmountHoursKeyReleased
 
     private void cbClerkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbClerkStateChanged
         checkEnabled();
     }//GEN-LAST:event_cbClerkStateChanged
 
     private void checkEnabled() {
         if (!tfEmployeeNumber.getText().isEmpty() &&
             isNumeric(tfEmployeeNumber.getText()) &&
             !tfFirstName.getText().isEmpty() &&
             !tfFamilyName.getText().isEmpty() &&
             !Exist() &&
             !RoosterProgramma.getInstance().decodePassword(tfPassword.getPassword()).isEmpty() &&
             (cbFullTime.isSelected() || cbClerk.isSelected() ||
             (cbPartTime.isSelected() && !tfAmountHours.getText().isEmpty() && isNumeric(tfAmountHours.getText())) ||
             (cbCallWorker.isSelected() && !tfMinAmountHours.getText().isEmpty() && isNumeric(tfMinAmountHours.getText()))))
         {
             btnSave.setEnabled(true);
         }
         else
         {
             btnSave.setEnabled(false);
         }
     }
 
     private boolean Exist() {
         int employeeNumber = Integer.parseInt(tfEmployeeNumber.getText());
         String familyName = tfFamilyName.getText().toLowerCase();
         String firstName = tfFirstName.getText().toLowerCase();
         boolean exists = false;
         for (Employee existingEmployee : RoosterProgramma.getQueryManager().getEmployees())
         {
             if (existingEmployee.getEmployeeNumber() == employeeNumber &&
                     (isAdd || employee.getEmployeeNumber() != employeeNumber))
             {   // If number is in use
                 lblNameInUse.setVisible(false);
                 exists = true;
                 lblNumberInUse.setVisible(true);
             }
             else if(existingEmployee.getFamilyName().toLowerCase().equals(familyName) && existingEmployee.getFirstName().toLowerCase().equals(firstName) &&
                     (isAdd || (!employee.getFirstName().toLowerCase().equals(firstName) || !employee.getFamilyName().toLowerCase().equals(familyName))))
             {   // If name is in use
                 lblNumberInUse.setVisible(false);
                 exists = true;
                 lblNameInUse.setVisible(true);
             }
             else
             {
                 lblNameInUse.setVisible(false);
                 lblNumberInUse.setVisible(false);
             }
             if (exists)
             {
                 return true;
             }
         }
         return false;
     }
 
     private boolean isNumeric (String strToTest) {
         boolean numeric = true;
         try {
             Double.parseDouble(strToTest);
         } catch (NumberFormatException nfe) {
             numeric = false;
         }
         return numeric;
     }
 
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnCancel;
     private javax.swing.JButton btnSave;
     private javax.swing.ButtonGroup buttonGroup;
     private javax.swing.JCheckBox cbCallWorker;
     private javax.swing.JCheckBox cbClerk;
     private javax.swing.JCheckBox cbFullTime;
     private javax.swing.JCheckBox cbPartTime;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel lblAmountHours;
     private javax.swing.JLabel lblCallWorker;
     private javax.swing.JLabel lblEmployeeNumber;
     private javax.swing.JLabel lblFamilyName;
     private javax.swing.JLabel lblFirstName;
     private javax.swing.JLabel lblFullTime;
     private javax.swing.JLabel lblMinAmountHours;
     private javax.swing.JLabel lblNameInUse;
     private javax.swing.JLabel lblNumberInUse;
     private javax.swing.JLabel lblPartTime;
     private javax.swing.JLabel lblWachtwoord;
     private javax.swing.JPanel pnlCallWorker;
     private javax.swing.JPanel pnlPartTime;
     private javax.swing.JTextField tfAmountHours;
     private javax.swing.JTextField tfEmployeeNumber;
     private javax.swing.JTextField tfFamilyName;
     private javax.swing.JTextField tfFirstName;
     private javax.swing.JTextField tfMinAmountHours;
     private javax.swing.JPasswordField tfPassword;
     // End of variables declaration//GEN-END:variables
 
 }
