 /* AUTO-GENERATED FILE.  DO NOT MODIFY.
  *
  * This class was automatically generated by the
  * aapt tool from the resource data it found.  It
  * should not be modified by hand.
  */
 
 package banana.slayers;
 
 public final class R {
     public static final class attr {
     }
     public static final class drawable {
         public static final int ic_launcher=0x7f020000;
     }
     public static final class id {
         public static final int button1=0x7f050000;
         public static final int button2=0x7f050001;
     }
     public static final class layout {
         public static final int game=0x7f030000;
         public static final int load_game=0x7f030001;
         public static final int main=0x7f030002;
         public static final int new_game=0x7f030003;
         public static final int quest=0x7f030004;
     }
     public static final class string {
         public static final int app_name=0x7f040000;
        public static final int load_game=0x7f040001;
        public static final int new_game=0x7f040002;
     }
 }
