 package item;
 
 import exception.OutsideTheGridException;
 import game.Inventory;
 import grid.Direction;
 import grid.Square;
 import grid.StartingPosition;
 
 import java.util.HashMap;
 import java.util.HashSet;
 import java.util.Set;
 
 import obstacle.ForceField;
 import obstacle.Obstacle;
 import obstacle.Wall;
 
 /**
  * This class represents a force field generator.
  * Force field generators are items that can be picked up and used by a player to generate a force field.
  * 
  * @author 	Groep 8
  * 
  * @version April 2013
  */
 public class ForceFieldGenerator extends PortableItem {
 	
 	/**
 	 * The force field corresponding with this force field generator.
 	 */
 	private Set<ForceField> forceFields = new HashSet<ForceField>();
 	
 	/**
 	 * This method returns the corresponding force field.
 	 * 
 	 * @return	this.forcefield
 	 * 			| The forcefield generated by this force field generator.
 	 */
 	public ForceField[] getForceFields() {
 		return forceFields.toArray(new ForceField[forceFields.size()]);
 	}
 
 	/**
 	 * This method sets the force field corresponding with this force field generator.
 	 * 
 	 * @param 	forcefield
 	 * 			The force field now corresponding with the force field generator.
 	 * 
 	 * @effect	The force field is set.
 	 * 			| new.forcefield = forcefield
 	 */
 	public void addForceField(ForceField forcefield) {
 		if(isValidForceField(forcefield)){
 			forceFields.add(forcefield);
 		}
 	}
 
 	public void removeForceField(ForceField forceField) {
		if(forceFields.contains(forceField)) {
			forceField.terminate();
			forceFields.remove(forceField);
		}
 	}
 	
 	public boolean isValidForceField(ForceField forceField){
 		return forceField != null;
 	}
 
 	/**
 	 * Checks whether the force field generator is visible on the grid.
 	 * 
 	 * @return 	True in this case.
 	 */
 	@Override
 	public boolean isVisible() {
 		return true;
 	}
 
 	/**
 	 * This method checks whether this force field generator can be on a square with the given items.
 	 * 
 	 * @param 	items
 	 * 			The items that are located on the square.
 	 * 
 	 * @return 	True if there isn't already a force field generator on the square.
 	 */
 	@Override
 	public boolean canBeOnSquare(Square square) {
 		boolean items = true;
 		for(Item item : square.getItems()) {
 			if(item instanceof ForceFieldGenerator && item != this) {
 				items = false;
 			}
 		}
 		
 		boolean obstacles = true;
 		for(Obstacle obstacle: square.getObstacles()) {
 			if(obstacle instanceof Wall) {
 				obstacles = false;
 			}
 		}
 		
 		return items && obstacles && !(square instanceof StartingPosition);
 	}
 	
 	/**
 	 * Checks whether the force field generator can be stepped on or not.
 	 * 
 	 * @return 	True when every generated force field is inactive, otherwise False.
 	 * 			| for each ForceField in forceFields
 	 * 			|	if(!forcefield.canEnter()) return false;
 	 */
 	@Override
 	public boolean canBeSteppedOn() {
 		for(ForceField forcefield: this.forceFields)
 			if(!(forcefield.canEnter()))
 				return false;
 		return true;
 	}
 	
 	/**
 	 * Uses a force field generator from the player.
 	 * 
 	 * @effect	The force field generator is used.
 	 * 			| isUsed() == True
 	 * @effect	The force field generator is placed on the field.
 	 * 			| getInventory().getOwner().getLocation().addItem(this);
 	 * @effect	The force field generator generates possible force fields.
 	 * 			| generateConnections()
 	 * @effect	Each generated force field observes the ActionNotifier
 	 * 			| for each ForceField in forceFields
 	 * 			|	ForceField.setObserver()
 	 */
 	public void onUse()	{
 		super.onUse();
 		if(getInventory() != null)
 			getInventory().getOwner().getLocation().addItem(this);
 		generateConnections();
 	}
 	
 	/**
 	 * This method specifies what happens when we remove a force field generator.
 	 * 
 	 * @effect	The force fields generated by this generator are deleted.
 	 */
 	@Override
 	public void onRemove() {
 		Set<ForceField> clone= new HashSet<ForceField>(forceFields);
 		for(ForceField forceField: clone)
 			forceField.terminate();
 		for(ForceField ff: clone)
 			removeForceField(ff);
 	}
 	
 	@Override
 	public void onAdd() {
 		generateConnections();
 	}
 
 	/**
 	 * Generates the possible force fields for this force field generator.
 	 */
 	public void generateConnections(){
 		HashMap<Square,Direction> squaresWithFF = new HashMap<Square,Direction>();
 		Square tempLoc = this.getLocation();
 		for(Direction dir: Direction.values()){
 			for(int i = 3; i > 0; i--){
 				try {
 					tempLoc = tempLoc.getNeighbour(dir);
 				} catch (OutsideTheGridException e) {
 					break;
 				}
 				if(!(tempLoc.canHaveAsObstacle(new ForceField())))
 					break;
 
 				for(Item item: tempLoc.getItems())
 					if(item instanceof ForceFieldGenerator)
 						squaresWithFF.put(tempLoc, dir);
 				
 			}
 			tempLoc = this.getLocation();
 		}
 		
 		for(Square sq: squaresWithFF.keySet()) {
 			ForceField forcefield = new ForceField();
 			forcefield.addSquares(this.getLocation(), sq, squaresWithFF.get(sq));
 			this.addForceField(forcefield);
 			for(Item item: sq.getItems())
 				if(item instanceof ForceFieldGenerator)
 					((ForceFieldGenerator) item).addForceField(forcefield);
 		}
 	}
 	
 	/**
 	 * This method returns whether the force field generator is active.
 	 * 
 	 * @return	True if the generator has an active force field, otherwise false.
 	 */
 	public boolean isActive(){
 		boolean rv = false;
 		if(this.forceFields.size() > 0){
 			for(ForceField ff: forceFields)
 				if(ff.getState().isActive())
 					rv = true;
 		}
 		return rv;
 		
 	}
 
 	/**
 	 * This method gives a string representation of the force field generator.
 	 * 
 	 * @return	A string representation of the generator.
 	 * 			| result == "Force Field Generator"
 	 */
 	@Override
 	public String toString() {
 		return "Force Field Generator";
 	}
 
 	@Override
 	public boolean canBeInInventory(Inventory inventory) {
 		return true;
 	}
 
 }
