 package com.jzeromq;
 
 import org.zeromq.jni.ZMQ;
 
 public enum SocketOptions {
    AFFINITY(ZMQ.AFFINITY), IDENTITY(ZMQ.IDENTITY), SUBSCRIBE(ZMQ.SUBSCRIBE), UNSUBSCRIBE(ZMQ.UNSUBSCRIBTE), RATE(
             ZMQ.RATE), RECOVERY_IVL(ZMQ.RECOVERY_IVL), SNDBUF(ZMQ.SNDBUF), RCVBUF(ZMQ.RCVBUF), RCVMORE(ZMQ.RCVMORE), FD(
             ZMQ.FD), EVENTS(ZMQ.EVENTS), TYPE(ZMQ.TYPE), LINGER(ZMQ.LINGER), RECONNECT_IVL(ZMQ.RECONNECT_IVL), BACKLOG(
             ZMQ.BACKLOG), RECONNECT_IVL_MAX(ZMQ.RECONNECT_IVL_MAX), MAXMSGSIZE(ZMQ.MAXMSGSIZE), SNDHWM(ZMQ.SNDHWM), RCVHWM(
             ZMQ.RCVHWM), MULTICAST_HOPS(ZMQ.MULTICAST_HOPS), RCVTIMEO(ZMQ.RCVTIMEO), SNDTIMEO(ZMQ.SNDTIMEO), IPV4ONLY(
             ZMQ.IPV4ONLY), LAST_ENDPOINT(ZMQ.LAST_ENDPOINT), ROUTER_MANDATORY(ZMQ.ROUTER_MANDATORY), TCP_KEEPALIVE(
             ZMQ.TCP_KEEPALIVE), TCP_KEEPALIVE_CNT(ZMQ.TCP_KEEPALIVE_CNT), TCP_KEEPALIVE_IDLE(ZMQ.TCP_KEEPALIVE_IDLE), TCP_KEEPALIVE_INTVL(
             ZMQ.TCP_KEEPALIVE_INTVL), TCP_ACCEPT_FILTER(ZMQ.TCP_ACCEPT_FILTER), DELAY_ATTACH_ON_CONNECT(
             ZMQ.DELAY_ATTACH_ON_CONNECT), XPUB_VERBOSE(ZMQ.XPUB_VERBOSE);
     private final int value;
 
     SocketOptions(int value) {
         this.value = value;
     }
 
     public int getValue() {
         return value;
     }
 }
