 package de.kasoki.swtrealtime;
 
 public enum BusStop {
 	// This list was automatic generated, if you find any mistakes please correct them! Thanks :)
 	AACHENERSTR("aache", "Aachener Str"),
 	ADASTR("adast", "Adastr"),
 	ADOLPHKOLPINGSTR("kolpi", "Adolph-Kolping-Str"),
 	AGROBSTR("agrob", "Agrobstr"),
 	ALBEROWE("alber", "Alberowe"),
 	ALTEROLLBAH("rollb", "Alte Rollbah"),
 	ALTENHEIMHAERENWIE("ALH", "Altenheim Haerenwie"),
 	ALTERORTSKER("ortsk", "Alter Ortsker"),
 	AMBEUTELWE("beute", "Am Beutelwe"),
 	AMBILDSTOC("bilds", "Am Bildstoc"),
 	AMHERRENBRUENNCHE("hbrue", "Am Herrenbruennche"),
 	AMKIEWELSBER("kiewe", "Am Kiewelsber"),
 	AMMARIAHO("MAH", "Am Mariaho"),
 	AMMOSELKA("mosel", "Am Moselka"),
 	AMMUEHLENTEIC("teich", "Am Muehlenteic"),
 	AMSANDBAC("sandb", "Am Sandbac"),
 	AMWASSERTUR("wturm", "Am Wassertur"),
 	AMWEIDENGRABENANF("wgran", "Am Weidengraben Anf"),
 	AMWEIDENGRABENEND("WGR", "Am Weidengraben End"),
 	AMWEIDENGRABENMIT("wgrmi", "Am Weidengraben Mit"),
 	AMWISSENSCHAFTSPAR("wpark", "Am Wissenschaftspar"),
 	AMALTENFLUGPLAT("flugp", "Am alten Flugplat"),
 	AMPHITHEATE("amphi", "Amphitheate"),
 	ANDERFELDPOR("feldp", "An der Feldpor"),
 	ANDERMAESWIES("maesw", "An der Maeswies"),
 	ANDERPFERDSWEID("weide", "An der Pferdsweid"),
 	ANDERSCHUL("TRS", "An der Schul"),
 	ANDERZIEGELE("ziege", "An der Ziegele"),
 	ANDREASSTR("taran", "Andreasstr"),
 	ANHEIERSTR("anhei", "Anheierstr"),
 	ARENATRIE("arena", "Arena Trie"),
 	ARNOLDISTR("arnol", "Arnoldistr"),
 	AUFMOHRBUESC("mohrb", "Auf Mohrbuesc"),
 	AUFDEMKIRCHSPIE("kirch", "Auf dem Kirchspie"),
 	AUFDERBAUSC("BAU", "Auf der Bausc"),
 	AUFDERHIL("HIL", "Auf der Hil"),
 	AUFDERJUENG("jueng", "Auf der Jueng"),
 	AUGUSTASTR("augus", "Augustastr"),
 	AVELERHO("avhof", "Avelerho"),
 	BALDUINSBRUNNENHB("baldu", "Balduinsbrunnen/HB"),
 	BARBARATHERME("barth", "Barbaratherme"),
 	BARBARAUFERROEMERB("baruf", "Barbaraufer/Roemerb"),
 	BEHRINGSTR("behri", "Behringstr"),
 	BENEDIKTINERSTR("bened", "Benediktinerstr"),
 	BERGSTR("bergs", "Bergstr"),
 	BERNHARDSTR("bernh", "Bernhardstr"),
 	BERTAR("berta", "Bertar"),
 	BETTEMBURGSTR("bette", "Bettemburgstr"),
 	BIEWERNOR("bnord", "Biewer-Nor"),
 	BIEWERSUE("bsued", "Biewer-Sue"),
 	BITBURGERSTR("bitbu", "Bitburger Str"),
 	BLUECHERSTR("bluec", "Bluecherstr"),
 	BLUETENWE("bluet", "Bluetenwe"),
 	BONHOCHWALDST("bohoc", "Bon-Hochwaldst"),
 	BONNEUSTR("boneu", "Bon-Neustr"),
 	BONTALSPERRENBLIC("BON", "Bon-Talsperrenblic"),
 	BONIFATIUSSTR("bonif", "Bonifatiusstr"),
 	BONNERSTR("bst", "Bonner Str"),
 	BRETTENBAC("brett", "Brettenbac"),
 	BRUCHHAUSENSTR("bhaus", "Bruchhausenstr"),
 	BUCHENWE("buche", "Buchenwe"),
 	BURGMUEHLENSTR("burgm", "Burgmuehlenstr"),
 	CASPAROLEVIANSTR("caspa", "Caspar-Olevian-Str"),
 	CASTELFORT("CAS", "Castelfort"),
 	CHARLOTTENSTR("charl", "Charlottenstr"),
 	CLARAVIEBIGSTR("viebi", "Clara-Viebig-Str"),
 	CUSANUSSTR("cusan", "Cusanusstr"),
 	DEUTSCHHERRENSTR("deuts", "Deutschherrenstr"),
 	DIEDENHOFENERSTR("diede", "Diedenhofener Str"),
 	DOMAENENSTR("domae", "Domaenenstr"),
 	DONAUSTR("donau", "Donaustr"),
 	EHRANGBAHNHOF("egbhf", "Ehrang-Bahnhof"),
 	EHRANGHINTEREHEIDE("EGH", "Ehrang-Hintere Heide"),
 	EHRANGSCHULE("egsch", "Ehrang-Schule"),
 	EHRANGSPORTPLATZ("sport", "Ehrang-Sportplatz"),
 	EHRANGUNTERFUEHRUNG("EGU", "Ehrang-Unterfuehrung"),
 	EHRANGERSTR("egstr", "Ehranger Str"),
 	EISENBAHNSTR("eisen", "Eisenbahnstr"),
 	EITELSBACHMITT("eitel", "Eitelsbach Mitt"),
 	EURENFRIEDHO("EUF", "Euren-Friedho"),
 	EURENHELENENBRUNNEN("EUH", "Euren-Helenenbrunne"),
 	EURENLUSTEINBSTR("EUL", "Euren-Lu.Steinb.Str"),
 	FACHHOCHSCHULE("FHS", "Fachhochschule"),
 	FANDELBOR("fande", "Fandelbor"),
 	FELDSTRMUTTERHAU("felds", "Feldstr./Mutterhau"),
 	FEYENGRAFSCHAF("FEY", "Feyen-Grafschaf"),
 	FILSCHMITT("fimit", "Filsch Mitt"),
 	FILSCHERHAEUSCHE("FIL", "Filscher Haeusche"),
 	FISCHWE("fiweg", "Fischwe"),
 	FRANZBUSSSTR("fbuss", "Franz-Buss-Str"),
 	FRANZGEORGSTR("fgeor", "Franz-Georg-Str"),
 	FREIHERRVSTEINST("freih", "Freiherr-v.Stein-St"),
 	FRIEDHOFSTR("fried", "Friedhofstr"),
 	FRITZQUANTSTR("quant", "Fritz-Quant-Str"),
 	FRITZVONWILLESTR("wille", "Fritz-von-Wille-Str"),
 	FROEBELSTR("froeb", "Froebelstr"),
 	FROEHLICHERSTR("froeh", "Froehlicherstr"),
 	GAMBRINUSSTR("gambr", "Gambrinusstr"),
 	GARTENFELDSTR("gfeld", "Gartenfeldstr"),
 	GEORGSTR("georg", "Georgstr"),
 	GILBERTSTR("GIL", "Gilbertstr"),
 	GOTTBILLSTR("VB", "Gottbillstr"),
 	GRAFREGINARSTR("grafr", "Graf-Reginar-Str"),
 	GUSIMBILSE("gubil", "Gus-Im Bilse"),
 	GUSIMFLUERCHE("guflu", "Gus-Im Fluerche"),
 	GUSLAERCHENWE("gulae", "Gus-Laerchenwe"),
 	GUSLINDENSTR("gulin", "Gus-Lindenstr"),
 	GUSROMIK("gurom", "Gus-Romik"),
 	GUSRUWERSTR("guruw", "Gus-Ruwerstr"),
 	GUSSCHUL("gusch", "Gus-Schul"),
 	GUSSOMMERAUERSTR("gusom", "Gus-Sommerauer Str"),
 	GUSTRIERERSTR("GUS", "Gus-Trierer Str"),
 	GUTENBERGSTR("ZEG", "Gutenbergstr"),
 	GUTWEILERIMBOORFEL("GUT", "Gutweiler-Im Boorfel"),
 	GUTWEILERKIRCH("gtkir", "Gutweiler-Kirch"),
 	HAENDELSTR("haend", "Haendelstr"),
 	HAFENSTR("hafst", "Hafenstr"),
 	HANDWERKSKAMME("HWK", "Handwerkskamme"),
 	HANSBOECKLERALLE("hansb", "Hans-Boeckler-Alle"),
 	HANSMSCHLEYERSTR("hansm", "Hans-M.Schleyer-Str"),
	HAUPTBAHNHO("HBF", "Hauptbahnho"),
 	HAUPTFRIEDHO("haupt", "Hauptfriedho"),
 	HEIDESTUF("heist", "Heidestuf"),
 	HEILIGKTREVERERST("HKT", "Heiligk.-Trevererst"),
 	HELENENSTR("helen", "Helenenstr"),
 	HINZENBURGMITT("HIN", "Hinzenburg Mitt"),
 	HOCHWALDSTR("hochw", "Hochwaldstr"),
 	HOCKWEILERMITT("HOK", "Hockweiler Mitt"),
 	HOEHENFRIEDHO("hofri", "Hoehenfriedho"),
 	HOFBER("hofbe", "Hofber"),
 	HOLZERATHMITT("holze", "Holzerath Mitt"),
 	HONTHEIMSTR("honth", "Hontheimstr"),
 	HOSPITALSMUEHL("hospi", "Hospitalsmuehl"),
 	HUNSRUECKSTR("hunsr", "Hunsrueckstr"),
 	IGELAMFEILENKREU("igfei", "Igel-Am Feilenkreu"),
 	IGELAMRODERKAM("igrod", "Igel-Am Roderkam"),
 	IGELAMSCHLEIDBER("igsbe", "Igel-Am Schleidber"),
 	IGELIGELERSAEUL("igsae", "Igel-Igeler Saeul"),
 	IGELKIRCH("igkir", "Igel-Kirch"),
 	IGELLAUBENSTR("iglau", "Igel-Laubenstr"),
 	IGELMOSELSTR("IGL", "Igel-Moselstr"),
 	IGELROEMERSTR("igroe", "Igel-Roemerstr"),
 	IGELSCHAUINSLAN("igsch", "Igel-Schauinslan"),
 	IGELWALDSTR("igwa", "Igel-Waldstr"),
 	IMAVELERTA("avtal", "Im Avelerta"),
 	IMHOPFENGARTE("HOP", "Im Hopfengarte"),
 	IMPAULINSGARTE("RUP", "Im Paulinsgarte"),
 	IMPFLANZGARTE("pflan", "Im Pflanzgarte"),
 	IMSCHAMMA("scham", "Im Schamma"),
 	IMSIEBENBOR("siebe", "Im Siebenbor"),
 	INDUSTRIEGEBZEWE("IZE", "Industriegeb.Zewe"),
 	IRSCHABZWEI("irabz", "Irsch Abzwei"),
 	IRSCHHOCKWEILERSTR("IRH", "Irsch-Hockweilerstr"),
 	IRSCHPROPSTE("IRP", "Irsch-Propste"),
 	IRSCHERBER("iberg", "Irscher Ber"),
 	IRSCHERHO("irhof", "Irscher Ho"),
 	IRSCHERMUEHL("irmue", "Irscher Muehl"),
 	IRSCHERSTR("irstr", "Irscher Str"),
 	ISBRUNNE("isbru", "Is-Brunne"),
 	ISBRUNNENSTR("isbst", "Is-Brunnenstr"),
 	ISZURKIESGRUB("iskie", "Is-Zur Kiesgrub"),
 	JAKOBKNEIPSTR("KEJ", "Jakob-Kneip-Str"),
 	JANUARIUSZICKSTR("jzick", "Januarius-Zick-Str"),
 	JOSEPHHAYDNSTR("haydn", "Joseph-Haydn-Str"),
 	JUNGENWAL("jwald", "Jungenwal"),
 	KAISERTHERME("KTH", "Kaisertherme"),
 	KANTSTR("kants", "Kantstr"),
 	KANZELSTR("ZEK", "Kanzelstr"),
 	KARLMARXHAU("KMH", "Karl-Marx-Hau"),
 	KARLSWE("karls", "Karlswe"),
 	KARRENBAC("karre", "Karrenbac"),
 	KASBAHNHO("kabhf", "Kas-Bahnho"),
 	KASBAHNHOFSTR("kabst", "Kas-Bahnhofstr"),
 	KASGEMEINDEPLAT("KAG", "Kas-Gemeindeplat"),
 	KASHAUSTIMPER("katim", "Kas-Haus Timper"),
 	KASSCHUL("kasch", "Kas-Schul"),
 	KASSPORTPLAT("kaspo", "Kas-Sportplat"),
 	KASWASSERHAEUSCHE("kawas", "Kas-Wasserhaeusche"),
 	KENNERWE("kenne", "Kenner We"),
 	KERNSCHHOEHENWEG1("hoeh1", "Kernsch.Hoehenweg "),
 	KERNSCHHOEHENWEG2("hoeh2", "Kernsch.Hoehenweg "),
 	KERNSCHEIDKIRCH("KER", "Kernscheid-Kirch"),
 	KEUNEGRUNDSCHUL("KEU", "Keune Grundschul"),
 	KLEEBURGERWE("OLK", "Kleeburger We"),
 	KOHLENSTR("kohle", "Kohlenstr"),
 	KOLONNENWE("KOL", "Kolonnenwe"),
 	KONRADADENAUERBR("adebr", "Konrad-Adenauer-Br"),
 	KONSTANTINBASILIK("KON", "Konstantin Basilik"),
 	KONZERSTR("konze", "Konzer Str"),
 	KORLNEUSTR("koneu", "Korl-Neustr"),
 	KORLZUMSTEINBRUC("koste", "Korl-Zum Steinbruc"),
 	KREUZFLU("kreuz", "Kreuzflu"),
 	KUERENZERSTR("KUE", "Kuerenzer Str"),
 	KUNOSTAPELSTR("kunos", "Kuno-Stapel-Str"),
 	KURFUERSTENSTR("kurfu", "Kurfuerstenstr"),
 	KYRIANDERSTR("kyria", "Kyrianderstr"),
 	LERHARDRINGAUSST("ludwi", "L.Erhard-Ring,Ausst"),
 	LAMBERTISTR("lambe", "Lambertistr"),
 	LANIMBUNGER("lgbun", "Lan-Im Bunger"),
 	LANKIRCH("lgkir", "Lan-Kirch"),
 	LANLOEWENERMUEHL("lgloe", "Lan-Loewener Muehl"),
 	LANMESENICHERSTR("lgmes", "Lan-Mesenicher Str"),
 	LANNEUSTR("lgneu", "Lan-Neustr"),
 	LANWASSERBILLIGERB("lgwas", "Lan-Wasserbilligerb"),
 	LANGFLU("langf", "Langflu"),
 	LAYWE("EGL", "Laywe"),
 	LEBENSHILF("LWT", "Lebenshilf"),
 	LENUSMARSSTR("lenus", "Lenus-Mars-Str"),
 	LEVELINGSTR("level", "Levelingstr"),
 	LIERSBERGHEINTZHO("lihei", "Liersberg-Heintzho"),
 	LIERSBERGKIRCH("LIE", "Liersberg-Kirch"),
 	LOEBSTR("loebs", "Loebstr"),
 	LUDWIGSIMONSTR("simon", "Ludwig-Simon-Str"),
 	LUXEMBURGERSTR("luxem", "Luxemburger Str"),
 	MAARSTR("maars", "Maarstr"),
 	MAEUSHECKERSCHUL("MHS", "Maeusheckerschul"),
 	MAEUSHECKERWE("MHW", "Maeusheckerwe"),
 	MAGNERICHSTR("magne", "Magnerichstr"),
 	MARIENHOLZSTR("mholz", "Marienholzstr"),
 	MARIENKRANKENHAU("mkrhs", "Marienkrankenhau"),
 	MARIENSAEUL("saeul", "Mariensaeul"),
 	MARKUSBER("mberg", "Markusber"),
 	MARKUSSTR("marku", "Markusstr"),
 	MARTINSCHUNCKSTR("schun", "Martin-Schunck-Str"),
 	MARTINSTR("marti", "Martinstr"),
 	MAXIMINERACH("maxim", "Maximinerach"),
 	MEILENSTR("meile", "Meilenstr"),
 	MERTABZWEITELSBAC("OVB", "Mert-Abzw.Eitelsbac"),
 	MERTBERGSTR("meber", "Mert-Bergstr"),
 	MERTDORFBRUNNE("medor", "Mert-Dorfbrunne"),
 	MERTEICHGRABE("MEE", "Mert-Eichgrabe"),
 	MERTGRUENHAU("megru", "Mert-Gruenhau"),
 	MERTSTADIONSTR("mesta", "Mert-Stadionstr"),
 	MERTZURFESTUN("mefes", "Mert-Zur Festun"),
 	MESENICHKIRCH("mskir", "Mesenich-Kirch"),
 	MESENICHTRIERERST("mstri", "Mesenich-Trierer St"),
 	MESSEPARKP_PLUS("MES", "Messepark P+"),
 	METZERALLE("MEZ", "Metzer Alle"),
 	MOHRENKOP("MOR", "Mohrenkop"),
 	MONAISERSTR("monai", "Monaiser Str"),
 	MORSCHEIDMITT("MOS", "Morscheid Mitt"),
 	MOSELSTADIO("stadio", "Moselstadio"),
 	MUEHLENSTR("muehl", "Muehlenstr"),
 	MUSTORSTR("musto", "Mustorstr"),
 	MZKIRCH("MZK", "Mz-Kirch"),
 	MZWINTERSDORFERST("mzwin", "Mz-Wintersdorfer St"),
 	NELLSPAR("NPA", "Nells Par"),
 	NELLSPARKPARKSTR("npapa", "Nells Park/Parkstr"),
 	NELLSTR("nells", "Nellstr"),
 	NIEDERKIRCHERSTR("nieder", "Niederkircher Str"),
 	NIEDERSTR("niest", "Niederstr"),
 	NIKOLAUSKOCHPLAT("NIK", "Nikolaus-Koch-Plat"),
 	NORDALLEEKRANKENHS("norda", "Nordallee/Krankenhs"),
 	NORDBA("nordb", "Nordba"),
 	P_AND_R_TRIERNOR("prnor", "P+R Trier Nor"),
 	PALLIENERSTR("palli", "Palliener Str"),
 	PELLINGERSTR("pelli", "Pellinger Str"),
 	PETERROTHPLAT("PRP", "Peter-Roth-Plat"),
 	PETERWUSTSTR("pwust", "Peter-Wust-Str"),
 	PETRISBER("PET", "Petrisber"),
 	PETRISBERGAUSSICH("aussi", "Petrisberg-Aussich"),
 	PFALZELBAHNHO("pfbhf", "Pfalzel-Bahnho"),
 	PFALZELELTZSTR("PFA", "Pfalzel-Eltzstr"),
 	PFERDEMARK("markt", "Pferdemark"),
 	PHILOSOPHENWE("philo", "Philosophenwe"),
 	PLUBAHNHO("plbhf", "Plu-Bahnho"),
 	PLUBAHNHOFSTR("plbst", "Plu-Bahnhofstr"),
 	PLUGUSTERATHERSTR("plgus", "Plu-Gusterather Str"),
 	PLUINDWEIDENWIE("plwei", "Plu-In d. Weidenwie"),
 	PLURUWERSTR("PLU", "Plu-Ruwerstr"),
 	PORTANIGR("PN", "Porta Nigr"),
 	QUINTSCHLOS("QUI", "Quint-Schlos"),
 	QUINTERSTR("quist", "Quinter Str"),
 	RATHAUSSTADTTHEATE("ratha", "Rathaus/Stadttheate"),
 	REMIGIUSSTR("remig", "Remigiusstr"),
 	RETZGRUBENWE("retzg", "Retzgrubenwe"),
 	RINGSTR("rings", "Ringstr"),
 	RIVBAUSBAC("ribau", "Riv-Bausbac"),
 	RIVMORSCHEIDERST("rimor", "Riv-Morscheider St"),
 	RIVERISMITT("rimit", "Riveris Mitt"),
 	ROEMERSTR("roest", "Roemerstr"),
 	ROTBACHSTR("ROT", "Rotbachstr"),
 	ROTHILDISSTR("rothi", "Rothildisstr"),
 	RUBENSTR("ruben", "Rubenstr"),
 	RUDOLFDIESELSTR("diese", "Rudolf-Diesel-Str"),
 	RUWERBAHNHO("rubhf", "Ruwer-Bahnho"),
 	RUWERSPORTPLAT("RUS", "Ruwer-Sportplat"),
 	RUWERERSTR("rustr", "Ruwererstr"),
 	SWTSTADTWERKETRIE("swtri", "SWT Stadtwerke Trie"),
 	SCHEFFELSTR("schef", "Scheffelstr"),
 	SCHIFFSTR("schif", "Schiffstr"),
 	SCHLOSSSTR("schlo", "Schlossstr"),
 	SCHOENBORNSTR("schoe", "Schoenbornstr"),
 	SCHUETZENSTR("schue", "Schuetzenstr"),
 	SCHWARZERWE("schwa", "Schwarzer We"),
 	SDALTENWE("sdalt", "Sd-Altenwe"),
 	SDHAUPTSTR("sdhau", "Sd-Hauptstr"),
 	SDKIRCH("sdkir", "Sd-Kirch"),
 	SDPLUWIGERHAMME("plham", "Sd-Pluwigerhamme"),
 	SEIFERSTR("seife", "Seiferstr"),
 	SPIROSTR("spiro", "Spirostr"),
 	STMATTHIA("MAT", "St. Matthia"),
 	STMEDAR("MED", "St. Medar"),
 	STPAULI("pauli", "St. Pauli"),
 	STURBA("urban", "St. Urba"),
 	STANNASTR("annas", "St.-Anna-Str"),
 	STMATTHIASAULSTR("matau", "St.-Matthias-Aulstr"),
 	STMATTHIASKIRCH("matki", "St.-Matthias-Kirch"),
 	STMERGENERSTR("merge", "St.-Mergener-Str"),
 	STADTBIBLIOTHE("bibli", "Stadtbibliothe"),
 	STEFANANDRESSTR("andre", "Stefan-Andres-Str"),
 	STEINBRUECKSTR("stein", "Steinbrueckstr"),
 	STEINSWE("stweg", "Steinswe"),
 	STRASSBURGERALLE("strass", "Strassburger Alle"),
 	SUEDALLEEKAISERSTR("SUE", "Suedallee/Kaiserstr"),
 	SUEDBAHNHO("SBF", "Suedbahnho"),
 	SUEDFRIEDHO("suedf", "Suedfriedho"),
 	SWALTESWEINHAU("swwei", "Sw-Altes Weinhau"),
 	SWBAHNHOFSTR("swbah", "Sw-Bahnhofstr"),
 	SWBERTRADASTR("swber", "Sw-Bertradastr"),
 	SWBRUNNE("swbru", "Sw-Brunne"),
 	SWERMESGRABE("swerm", "Sw-Ermesgrabe"),
 	SWLANGFUHRSTR("SWE", "Sw-Langfuhrstr"),
 	TARFKCARSTENSST("TAK", "Tarf.-K.Carstens-St"),
 	TARFLERHARDRIN("TAL", "Tarf.-L.Erhard-Rin"),
 	TARFORSTERSTR("tarst", "Tarforster Str"),
 	TAUBENBER("taube", "Taubenber"),
 	TEMPELHERRENSTR("teher", "Tempelherrenstr"),
 	TEMPELWE("teweg", "Tempelwe"),
 	THEODORHEUSSALLE("THA", "Theodor-Heuss-Alle"),
 	THYRSUSSTR("thyrs", "Thyrsusstr"),
 	TIERGARTE("OLT", "Tiergarte"),
 	TOEPFERSTR("toepf", "Toepferstr"),
 	TREBETASTR("trebe", "Trebetastr"),
 	TREVIRI("TRV", "Treviri"),
 	TRIERGALERI("galer", "Trier Galeri"),
 	TRIERERHAFE("hafen", "Trierer Hafe"),
 	TRIERWEILERWE("TWW", "Trierweilerwe"),
 	TRIMHOFAUGUSTSTR("TRH", "Trim.Hof-August.str"),
 	UNIVERSITAE("UNI", "Universitae"),
 	UNIVERSITAETCAMPUS("UC2", "Universitaet Campus"),
 	UNIVERSITAETHAUPTG("UNH", "Universitaet Hauptg"),
 	UNIVERSITAETMENS("UNM", "Universitaet Mens"),
 	UNIVERSITAETPARKPL("unipa", "Universitaet Parkpl"),
 	UNIVERSITAETSUE("UNS", "Universitaet Sue"),
 	VBREALMARK("vbrea", "VB-Real-Mark"),
 	VBTESTPLAT("vbtes", "VB-Testplat"),
 	VBTOR("vbto3", "VB-Tor "),
 	VBZENTRAL("vbzen", "VB-Zentral"),
 	VILLAREVERCHO("villa", "Villa Revercho"),
 	VORDEREHEID("vheid", "Vordere Heid"),
 	WALDAMSPORTPLAT("WAL", "Wald-Am Sportplat"),
 	WALDAUFDEMFLUERCHE("waflu", "Wald-Auf dem Fluerche"),
 	WALDBAHNHO("wabhf", "Wald-Bahnho"),
 	WALDGEMEINDEPLAT("wagem", "Wald-Gemeindeplat"),
 	WALDGEWERBEGEBIE("wagew", "Wald-Gewerbegebie"),
 	WALDINDERACH("waach", "Wald-In der Ach"),
 	WALDINDERLA("walay", "Wald-In der La"),
 	WALDOBEREKIRCHST("wakir", "Wald-Obere Kirchst"),
 	WALDPAETSCHERWE("wapae", "Wald-Paetscher We"),
 	WALDROSENBUNGER("waros", "Wald-Rosenbunger"),
 	WALDSCHUL("wasch", "Wald-Schul"),
 	WALDWEINBERGSWE("wawei", "Wald-Weinbergswe"),
 	WALDZOLLWE("wazol", "Wald-Zollwe"),
 	WALDSTR("walds", "Waldstr"),
 	WALLENBACHSTR("walle", "Wallenbachstr"),
 	WASSERBILLIGERSTR("wbill", "Wasserbilliger Str"),
 	WASSERWE("waweg", "Wasserwe"),
 	WEISMARKPFAHLWEIHE("WEI", "Weismark-Pfahlweihe"),
 	WENZELBACHSTR("wenze", "Wenzelbachstr"),
 	WERDINGSTR("werdi", "Werdingstr"),
 	WESTBAHNHO("WBF", "Westbahnho"),
 	WILHLEUSCHNERSTR("WLE", "Wilh.-Leuschner-Str"),
 	WINKIRCH("WDK", "Win-Kirch"),
 	WINLINDENSTR("wdlin", "Win-Lindenstr"),
 	WINWEINBERGSWE("wdwei", "Win-Weinbergswe"),
 	WISPORTSTR("wispo", "Wisportstr"),
 	WOLFSBER("WOB", "Wolfsber"),
 	WOLKERSTR("wolke", "Wolkerstr"),
 	ZEWENFRIEDHO("ZEF", "Zewen-Friedho"),
 	ZUMHELLBER("hellb", "Zum Hellber"),
 	ZUMROEMERSPRUDE("sprud", "Zum Roemersprude"),
 	ZURLAUBENERUFE("ZUR", "Zurlaubener Ufe"),
 	ZURMAIENERSTRNORD("zurma", "Zurmaiener Str.Nord");
 	
 	private String stopCode;
 	private String name;
 	
 	BusStop(String stopCode, String name) {
 		this.stopCode = stopCode;
 		this.name = name;
 	}
 	
 	public String getStopCode() {
 		return this.stopCode;
 	}
 }
