 package graphemesToPhonemesConverters;
 
 public class GraphemesToPolishPhonemesConverter extends NaiveGraphemesToPhonemesConverter
 {
 	private final static String[][][] polishGraphemes = new String[][][]{
 		{{"a"}, {"a"}},
 		{{"ą"}, {"o ł"}},
 		{{"b"}, {"b", "p"}},
 		{{"c"}, {"c"}},
 		{{"ci"}, {"ć i"}},
 		{{"cia"}, {"ć j a"}},
 		{{"cią"}, {"ć j o ł"}},
 		{{"cie"}, {"ć j e"}},
 		{{"cię"}, {"ć j e ł"}},
 		{{"cio"}, {"ć j o"}},
 		{{"ció"}, {"ć j u"}},
 		{{"ciu"}, {"ć j u"}},
 		{{"ć"}, {"ć"}},
 		{{"cz"}, {"cz"}},
 		{{"d"}, {"d"}},
 		{{"di"}, {"d i"}},
 		{{"dia"}, {"d j a"}},
 		{{"dią"}, {"d j o ł"}},
 		{{"die"}, {"d j e"}},
 		{{"dię"}, {"d j e ł"}},
 		{{"dio"}, {"d j o"}},
 		{{"dió"}, {"d j u"}},
 		{{"diu"}, {"d j u"}},
 		{{"dz"}, {"d z"}},
 		{{"dzi"}, {"d ź i"}},
 		{{"dzia"}, {"d ź j a"}},
 		{{"dzią"}, {"d ź j o ł"}},
 		{{"dzie"}, {"d ź j e"}},
 		{{"dzię"}, {"d ź j e ł"}},
 		{{"dzio"}, {"d ź j o"}},
 		{{"dzió"}, {"d ź j u"}},
 		{{"dziu"}, {"d ź j u"}},
 		{{"dż"}, {"d ż"}},
 		{{"dź"}, {"d ź"}},
 		{{"e"}, {"e"}},
 		{{"ę"}, {"e ł"}},
 		{{"f"}, {"f"}},
 		{{"fi"}, {"f i"}},
 		{{"fia"}, {"f j a"}},
 		{{"fią"}, {"f j o ł"}},
 		{{"fie"}, {"f j e"}},
 		{{"fię"}, {"f j e ł"}},
 		{{"fio"}, {"f j o"}},
 		{{"fió"}, {"f j u"}},
 		{{"fiu"}, {"f j u"}},
 		{{"g"}, {"g"}},
 		{{"gi"}, {"g i"}},
 		{{"gia"}, {"g j a"}},
 		{{"gią"}, {"g j o ł"}},
 		{{"gie"}, {"g j e"}},
 		{{"gię"}, {"g j e ł"}},
 		{{"gio"}, {"g j o"}},
 		{{"gió"}, {"g j u"}},
 		{{"giu"}, {"g j u"}},
 		{{"h"}, {"h"}},
 		{{"hi"}, {"h i"}},
 		{{"hia"}, {"h j a"}},
 		{{"hią"}, {"h j o ł"}},
 		{{"hie"}, {"h j e"}},
 		{{"hię"}, {"h j e ł"}},
 		{{"hio"}, {"h j o"}},
 		{{"hió"}, {"h j u"}},
 		{{"hiu"}, {"h j u"}},
 		{{"ch"}, {"h"}},
 		{{"chi"}, {"h i"}},
 		{{"chia"}, {"h j a"}},
 		{{"chią"}, {"h j o ł"}},
 		{{"chie"}, {"h j e"}},
 		{{"chię"}, {"h j e ł"}},
 		{{"chio"}, {"h j o"}},
 		{{"chió"}, {"h j u"}},
 		{{"chiu"}, {"h j u"}},
 		{{"chrz"}, {"h sz"}},
 		{{"chż"}, {"h sz"}},
 		{{"i"}, {"i"}},
 		{{"j"}, {"j"}},
 		{{"k"}, {"k"}},
 		{{"ki"}, {"k i"}},
 		{{"kia"}, {"k j a"}},
 		{{"kią"}, {"k j o ł"}},
 		{{"kie"}, {"k j e"}},
 		{{"kię"}, {"k j e ł"}},
 		{{"kio"}, {"k j o"}},
 		{{"kió"}, {"k j u"}},
 		{{"kiu"}, {"k j u"}},
 		{{"krz"}, {"k sz"}},
 		{{"kż"}, {"k sz"}},
 		{{"l"}, {"l"}},
 		{{"ł"}, {"ł"}},
 		{{"m"}, {"m"}},
 		{{"mi"}, {"m i"}},
 		{{"mia"}, {"m j a"}},
 		{{"mią"}, {"m j o ł"}},
 		{{"mie"}, {"m j e"}},
 		{{"mię"}, {"m j e ł"}},
 		{{"mio"}, {"m j o"}},
 		{{"mió"}, {"m j u"}},
 		{{"miu"}, {"m j u"}},
 		{{"n"}, {"n"}},
 		{{"ni"}, {"ń i"}},
 		{{"nia"}, {"ń j a"}},
 		{{"nią"}, {"ń j o ł"}},
 		{{"nie"}, {"ń j e"}},
 		{{"nię"}, {"ń j e ł"}},
 		{{"nio"}, {"ń j o"}},
 		{{"nió"}, {"ń j u"}},
 		{{"niu"}, {"ń j u"}},
 		{{"ń"}, {"ń"}},
 		{{"o"}, {"o"}},
 		{{"ó"}, {"u"}},
 		{{"p"}, {"p"}},
 		{{"pi"}, {"p i"}},
 		{{"pia"}, {"p j a"}},
 		{{"pią"}, {"p j o ł"}},
 		{{"pie"}, {"p j e"}},
 		{{"pię"}, {"p j e ł"}},
 		{{"pio"}, {"p j o"}},
 		{{"pió"}, {"p j u"}},
 		{{"piu"}, {"p j u"}},
 		{{"prz"}, {"p sz"}},
 		{{"r"}, {"r"}},
 		{{"ri"}, {"r i"}},
 		{{"ria"}, {"r j a"}},
 		{{"rią"}, {"r j o ł"}},
 		{{"rie"}, {"r j e"}},
 		{{"rię"}, {"r j e ł"}},
 		{{"rio"}, {"r j o"}},
 		{{"rió"}, {"r j u"}},
 		{{"riu"}, {"r j u"}},
 		{{"rz"}, {"ż"}},
 		{{"s"}, {"s"}},
 		{{"sia"}, {"ś j a"}},
 		{{"sią"}, {"ś j o ł"}},
 		{{"sie"}, {"ś j e"}},
 		{{"się"}, {"ś j e ł"}},
 		{{"sio"}, {"ś j o"}},
 		{{"sió"}, {"ś j u"}},
 		{{"siu"}, {"ś j u"}},
 		{{"sz"}, {"sz"}},
 		{{"ś"}, {"ś"}},
 		{{"t"}, {"t"}},
 		{{"ti"}, {"t i"}},
 		{{"tia"}, {"t j a"}},
		{{"tią"}, {"t j o ł"}},
 		{{"tie"}, {"t j e"}},
		{{"tię"}, {"t j e ł"}},
 		{{"tio"}, {"t j o"}},
 		{{"tió"}, {"t j u"}},
 		{{"tiu"}, {"t j u"}},
 		{{"trz"}, {"t sz"}},
 		{{"tż"}, {"t sz"}},
 		{{"u"}, {"u"}},
 		{{"v"}, {"w", "f"}},
 		{{"w"}, {"w", "f"}},
 		{{"y"}, {"y"}},
 		{{"z"}, {"z", "s"}},
         {{"zi"}, {"ź i"}},
         {{"zia"}, {"ź j a"}},
        {{"zią"}, {"ź j o ł"}},
         {{"zie"}, {"ź j e"}},
        {{"zię"}, {"ź j e ł"}},
         {{"zio"}, {"ź j o"}},
         {{"zió"}, {"ź j u"}},
         {{"ziu"}, {"ź j u"}},
 		{{"ż"}, {"ż"}},
 		{{"ź"}, {"ź"}},
 		{{"ü"}, {"u"}}
 	};
 
 	public GraphemesToPolishPhonemesConverter()
 	{
 		super(polishGraphemes);
 	}
 
 }
