 /* AUTO-GENERATED FILE.  DO NOT MODIFY.
  *
  * This class was automatically generated by the
  * aapt tool from the resource data it found.  It
  * should not be modified by hand.
  */
 
 package com.example.busstop;
 
 public final class R {
     public static final class attr {
     }
     public static final class drawable {
         public static final int ic_action_search=0x7f020000;
         public static final int ic_launcher=0x7f020001;
     }
     public static final class id {
         public static final int Browse=0x7f070005;
        public static final int FavHist=0x7f070006;
         public static final int Favorites=0x7f070001;
         public static final int History=0x7f070002;
         public static final int LinearLayout=0x7f070000;
         public static final int ListView=0x7f070003;
         public static final int MakeTrip=0x7f070004;
         public static final int menu_settings=0x7f070007;
     }
     public static final class layout {
         public static final int activity_browse=0x7f030000;
         public static final int activity_fav_history=0x7f030001;
         public static final int activity_favorites=0x7f030002;
         public static final int activity_history=0x7f030003;
         public static final int activity_main=0x7f030004;
         public static final int activity_plan_trip=0x7f030005;
     }
     public static final class menu {
         public static final int activity_browse=0x7f060000;
         public static final int activity_fav_history=0x7f060001;
         public static final int activity_favorites=0x7f060002;
         public static final int activity_history=0x7f060003;
         public static final int activity_main=0x7f060004;
         public static final int activity_plan_trip=0x7f060005;
     }
     public static final class string {
         public static final int app_name=0x7f040000;
         public static final int button_browse=0x7f040002;
         public static final int button_fav_hist=0x7f040003;
         public static final int button_favorites=0x7f040004;
         public static final int button_history=0x7f040005;
         public static final int button_plan_trip=0x7f040001;
         public static final int hello_world=0x7f04000a;
         public static final int menu_settings=0x7f040008;
         public static final int text_browse=0x7f040007;
         public static final int text_plan_trip=0x7f040006;
         public static final int title_activity_browse=0x7f04000c;
         public static final int title_activity_fav_history=0x7f04000e;
         public static final int title_activity_favorites=0x7f04000f;
         public static final int title_activity_history=0x7f04000d;
         public static final int title_activity_main=0x7f040009;
         public static final int title_activity_plan_trip=0x7f04000b;
     }
     public static final class style {
         public static final int AppTheme=0x7f050000;
     }
 }
