 package my.triviagame.gui;
 
 import com.google.common.collect.Lists;
 import java.awt.Cursor;
 import java.util.ArrayList;
 import java.util.Collection;
 import java.util.List;
 import java.util.logging.Level;
 import java.util.logging.Logger;
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;
 import javax.swing.JOptionPane;
 import javax.swing.JTable;
 import javax.swing.SwingUtilities;
 import javax.swing.table.DefaultTableModel;
 import my.triviagame.bll.Database;
 import my.triviagame.dal.*;
 
 public class Discover extends javax.swing.JFrame {
     
     public static Pattern SEARCH_TOKENIZER = Pattern.compile("([^\\s\"]+)|(\"[^\"]+\")");
     
     private Thread thread = null;
     private Collection<ITrackDescriptor> results;
 
     /**
      * Creates new form Discover
      */
     public Discover() {
         initComponents();
         setLocationRelativeTo(null);
         this.getRootPane().setDefaultButton(jButton1);
         this.jTextFieldSearchBox.selectAll();
         this.jLabelNoResults.setVisible(false);
         jTextFieldSearchResults.setAutoCreateRowSorter(true);
     }
 
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
 
         jPanel1 = new javax.swing.JPanel();
         jLabel1 = new javax.swing.JLabel();
         jTextFieldSearchBox = new javax.swing.JTextField();
         jButton1 = new javax.swing.JButton();
         jLabel2 = new javax.swing.JLabel();
         jScrollPane1 = new javax.swing.JScrollPane();
         jTextFieldSearchResults = new javax.swing.JTable();
         jLabelNoResults = new javax.swing.JLabel();
 
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
         setResizable(false);
 
         jPanel1.setBackground(new java.awt.Color(255, 255, 255));
 
         jLabel1.setText("Please enter text to search:");
 
         jButton1.setText("Search!");
         jButton1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton1ActionPerformed(evt);
             }
         });
 
         jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/triviagame/gui/resources/Discover.jpg"))); // NOI18N
         jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
 
         jTextFieldSearchResults.setModel(new javax.swing.table.DefaultTableModel(
             new Object [][] {
 
             },
             new String [] {
                 "Song", "Artist", "Album", "Album Artist", "Track #", "Genre", "Length"
             }
         ) {
             Class[] types = new Class [] {
                 java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
             };
             boolean[] canEdit = new boolean [] {
                 false, false, false, false, false, false, false
             };
 
             public Class getColumnClass(int columnIndex) {
                 return types [columnIndex];
             }
 
             public boolean isCellEditable(int rowIndex, int columnIndex) {
                 return canEdit [columnIndex];
             }
         });
         jTextFieldSearchResults.setSurrendersFocusOnKeystroke(true);
         jTextFieldSearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseClicked(java.awt.event.MouseEvent evt) {
                 myHandler(evt);
             }
         });
         jScrollPane1.setViewportView(jTextFieldSearchResults);
 
         jLabelNoResults.setForeground(new java.awt.Color(255, 0, 0));
         jLabelNoResults.setText("Sorry, we couldn't find what you were looking for. Please refine your search and try again.");
 
         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
         jPanel1.setLayout(jPanel1Layout);
         jPanel1Layout.setHorizontalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
                         .addContainerGap())
                     .addGroup(jPanel1Layout.createSequentialGroup()
                         .addComponent(jLabel1)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(jTextFieldSearchBox)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addComponent(jButton1)
                         .addGap(52, 52, 52))))
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(453, 453, 453)
                         .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jLabelNoResults, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                 .addGap(0, 0, Short.MAX_VALUE))
         );
         jPanel1Layout.setVerticalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(13, 13, 13)
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(jTextFieldSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jButton1))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                 .addComponent(jLabelNoResults)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap())
         );
 
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addContainerGap())
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addContainerGap())
         );
 
         pack();
     }// </editor-fold>//GEN-END:initComponents
 
     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (!SwingUtilities.isEventDispatchThread())
         {
             throw new RuntimeException();
         }
 
         if (jTextFieldSearchBox.getText().isEmpty())
         {
             JOptionPane.showMessageDialog(this,"Please enter text to search.");
             jTextFieldSearchBox.selectAll();
             return;
         }
         
         String textToSearch = jTextFieldSearchBox.getText();
         List<String> keywordsList = Lists.newArrayList();
         Matcher m = SEARCH_TOKENIZER.matcher(textToSearch);
         while (m.find()) {
             if (m.group(1) != null) {
                 keywordsList.add(m.group(1));
             } else {
                 keywordsList.add(m.group(2));
             }
         }
        String[] keywords = (String[])keywordsList.toArray();
 
         jButton1.setEnabled(false);
         jPanel1.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         jTextFieldSearchBox.setEnabled(false);
         jTextFieldSearchResults.setEnabled(false);
         thread = new Thread(new myThread(keywords));
         thread.start();
     }//GEN-LAST:event_jButton1ActionPerformed
 
     private void myHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myHandler
         if (evt.getClickCount() != 2)
         {
             return;
         }
         
         if (evt.getButton() != java.awt.event.MouseEvent.BUTTON1)
         {
             return;
         }
 
         JTable table;
         try
         {
             table = (JTable)evt.getSource();
         }
         catch (Exception ex)
         {
             return;
         }
         
         int selectedRowIndex = table.getSelectedRow();
         ITrackDescriptor trackDesc = getTrackDescByRow(selectedRowIndex, table);
         IDAL dataAccessLayer = Database.getDataAccessLayer();
         int albumId = trackDesc.getAlbumId();
         List<Integer> albumIds = new ArrayList<Integer>();
         albumIds.add(albumId);
         
         List<IAlbumDescriptor> albumDescriptors = null;
         try {
             albumDescriptors = dataAccessLayer.getAlbumDescriptors(albumIds);
         } catch (DALException ex) {
             Logger.getLogger(Discover.class.getName()).log(Level.SEVERE, null, ex);
         }
         IAlbumDescriptor albumDesc = albumDescriptors.get(0);
         List<ITrackDescriptor> trackDescriptors = null;
         try {
             trackDescriptors = dataAccessLayer.getAlbumTrackDescriptors(albumDesc);
         } catch (DALException ex) {
             Logger.getLogger(Discover.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         AddUpdate addUpdateForm = new AddUpdate(albumDesc, trackDescriptors);
         addUpdateForm.show();
     }//GEN-LAST:event_myHandler
 
     private ITrackDescriptor getTrackDescByRow(int selectedRowIndex, JTable table)
     {
         String song = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,0).toString();
         String artist = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,1).toString();
         String album = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,2).toString();
         String albumArtist = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,3).toString();
         String trackNum = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,4).toString();
         String genre = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,5).toString();
         String length = ((DefaultTableModel)table.getModel()).getValueAt(selectedRowIndex,6).toString();
         
         for (ITrackDescriptor currTrack : results)
         {
             int s = currTrack.getLengthInSeconds();
             if ((currTrack.getTitle().equals(song)) &&
                 (currTrack.getAlbumArtist().equals(albumArtist)) &&
                 (currTrack.getArtistName().equals(artist)) &&
                 (currTrack.getAlbumName().equals(album)) &&
                 (String.valueOf(currTrack.getTrackNum()).equals(trackNum)) &&
                 (currTrack.getGenre().equals(genre)) &&
                 (String.format("%d:%02d:%02d", s/3600, (s%3600)/60, (s%60)).equals(length)))
             {
                 return currTrack;
             }
         }
         
         return null;
     }
 
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
         /*
          * Set the Nimbus look and feel
          */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         /*
          * If Nimbus (introduced in Java SE 6) is not available, stay with the
          * default look and feel. For details see
          * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
          */
         try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ClassNotFoundException ex) {
             java.util.logging.Logger.getLogger(Discover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(Discover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(Discover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(Discover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>
 
         /*
          * Create and display the form
          */
         java.awt.EventQueue.invokeLater(new Runnable() {
 
             public void run() {
                 new Discover().setVisible(true);
             }
         });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabelNoResults;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTextField jTextFieldSearchBox;
     private javax.swing.JTable jTextFieldSearchResults;
     // End of variables declaration//GEN-END:variables
     
     private void SetResult()
     {
         jPanel1.setCursor(null);
         jButton1.setEnabled(true);
         jTextFieldSearchBox.setEnabled(true);
         jTextFieldSearchResults.setEnabled(true);
 
         ((DefaultTableModel)jTextFieldSearchResults.getModel()).setRowCount(0);
 
         jLabelNoResults.setVisible(results.isEmpty());
         if (results.isEmpty())
         {
             jTextFieldSearchBox.selectAll();
             return;
         }
         
         Object[] resultsArr = results.toArray();
         for (int i = 0; i < resultsArr.length; i++)
         {
             TrackDescriptor trackDesc = (TrackDescriptor)resultsArr[i];
             
             int s =trackDesc.getLengthInSeconds();
             String[] currTrackData = new String[] {
                 trackDesc.getTitle(),
                 trackDesc.getArtistName(),
                 trackDesc.getAlbumName(),
                 trackDesc.getAlbumArtist(),
                 String.valueOf(trackDesc.getTrackNum()),
                 trackDesc.getGenre(),
                 String.format("%d:%02d:%02d", s/3600, (s%3600)/60, (s%60))};
             ((DefaultTableModel)jTextFieldSearchResults.getModel()).addRow(currTrackData);
         }
     }
 
     private void SetResultSafely()
     {
         Runnable r = new Runnable()
         {
             @Override
             public void run()
             {
                 try
                 {
                     SetResult();
                 } catch (Exception ex)
                 {
                     Logger.getLogger(Discover.class.getName()).log(Level.SEVERE, null, ex);
                 } 
             }
         };
 
         SwingUtilities.invokeLater(r);
     }
 
     private class myThread implements Runnable
     {
         private String[] keywords;
 
         public myThread(String[] keywords)
         {
             this.keywords = keywords;
         }
 
         @Override
         public void run()
         {
             IDAL dataAccessLayer = Database.getDataAccessLayer();
             results = null;
             try {
                 results = my.triviagame.bll.Discover.getTrackDescriptors(dataAccessLayer, keywords);
             } catch (DALException ex) {
                 Logger.getLogger(Discover.class.getName()).log(Level.SEVERE, null, ex);
             }
 
             SetResultSafely();
         }
     }
 
 }
