 package edu.upenn.cis350;
 
 import java.util.ArrayList;
 import java.util.List;
 
 import android.os.Parcel;
 import android.os.Parcelable;
 
 
 // POJO to hold all event data, eventually to be put into a sqlite DB
 public class EventPOJO implements Parcelable{
 	
 	private String eventTitle;
 	private String eventDesc;
 	private String eventActions;
 	private String start; //TODO timestamp?
 	private String end;
 	private List<String> affils;
 	private List<String> systems;
 	private int severity;
 	private String contact1;
 	private String contact2;
 	private String type;
 	private List<MessagePOJO> messages = new ArrayList<MessagePOJO>();
 	//TODO List of messages as Strings or Message objects?
 	
 	//Used to regenerate object
 	public static final Parcelable.Creator<EventPOJO> CREATOR = new Parcelable.Creator<EventPOJO>() {
         public EventPOJO createFromParcel(Parcel in) {
             return new EventPOJO(in);
         }
 
         public EventPOJO[] newArray(int size) {
             return new EventPOJO[size];
         }
     };
 
 	
 	public EventPOJO(){
 		affils = new ArrayList<String>();
 		systems = new ArrayList<String>();
 	}
 	
 	public EventPOJO(Parcel in){
 		eventTitle = in.readString();
 		eventDesc = in.readString();
 		eventActions = in.readString();
 		start = in.readString();
 		end = in.readString();
 		affils = new ArrayList<String>();
 		in.readList(affils, null);
 		systems = new ArrayList<String>();
 		in.readList(systems, null);
 		severity = in.readInt();
 		contact1 = in.readString();
 		contact2 = in.readString();
 		type = in.readString();
		in.readList(messages, null);
 	}
 	
 	///////// SETTER METHODS /////////////
 	
 	public void setEventTitle(String name){
 		eventTitle = name;
 	}
 	
 	public void setEventDesc(String desc){
 		eventDesc = desc;
 	}
 	
 	public void setEventActions(String actions){
 		eventActions = actions;
 	}
 	
 	public void setStart(String time){
 		start = time;
 	}
 
 	public void setEnd(String time){
 		end = time;
 	}
 	
 	public void addToAffils(String affil){
 		affils.add(affil);
 	}
 	
 	public void addToSystems(String system){
 		systems.add(system);
 	}
 	
 	public void addToMessages(MessagePOJO mess){
 		messages.add(mess);
 	}
 	
 	public void setSeverity(int sev){
 		severity = sev;
 	}
 	
 	public void setContact1(String contact){
 		contact1 = contact;
 	}
 	
 	public void setContact2(String contact){
 		contact2 = contact;
 	}
 	
 	public void setType(String type){
 		this.type = type;
 	}
 	
 	//////////// GETTER METHODS /////////////
 	
 	public String getEventTitle(){
 		return eventTitle;
 	}
 	
 	public String getEventDesc(){
 		return eventDesc;
 	}
 	
 	public String getEventActions(){
 		return eventActions;
 	}
 	
 	public String getStart(){
 		return start;
 	}
 	
 	public String getEnd(){
 		return end;
 	}
 	
 	public List<String> getAffils(){
 		return affils;
 	}
 	
 	public List<String> getSystems(){
 		return systems;
 	}
 	
 	public List<MessagePOJO> getMessages(){
 		return messages;
 	}
 	
 	public int getSeverity(){
 		return severity;
 	}
 	
 	public String getContact1(){
 		return contact1;
 	}
 	
 	public String getContact2(){
 		return contact2;
 	}
 	
 	public String getType(){
 		return type;
 	}
 
 	// Autogenerated methods
 	@Override
 	public int describeContents() {
 		// TODO Auto-generated method stub
 		return hashCode();
 	}
 
 	// flatten each field
 	@Override
 	public void writeToParcel(Parcel dest, int flags) {
 		// TODO Auto-generated method stub
 		dest.writeString(eventTitle);
 		dest.writeString(eventDesc);
 		dest.writeString(eventActions);
 		dest.writeString(start);
 		dest.writeString(end);
 		dest.writeList(affils);
 		dest.writeList(systems);
 		dest.writeInt(severity);
 		dest.writeString(contact1);
 		dest.writeString(contact2);
 		dest.writeString(type);
 		dest.writeList(messages);
 	}
 	
 	
 	
 	
 	
 	
 	
 	
 	
 }
